In [2]:
import pandas as pd
import numpy as np
df = pd.read_excel('/content/cases_train2.xlsx')
df_test_cases = pd.read_excel('/content/Test1.xlsx')
df['Оценка'] = df['Оценка'].round().astype('Int64')
df_test_cases['Оценка'] = df_test_cases['Оценка'].round().astype('Int64')
#df = pd.read_excel("/content/good table.xlsx")
df.head(100)

,Кейс,Решение,Решение кейса,ЦА,Проработка решения,Финансовая модель и метрики,Анализ рисков,Доказательства,Оценка
0,1,1,Я выбрал отрасль туризма и гостиничного бизнес...,1,1,1,1,1,1
1,1,2,Я выбрал для разработки отраслевого решения сф...,2,2,2,2,2,2
2,1,4,"Я выбрал отрасль образования, а именно сегмент...",2,4,4,3,3,3
3,1,5,Я выбрал отрасль розничной торговли продуктами...,1,3,2,2,1,2
4,1,6,Я выбрал для отраслевого решения сферу гостини...,3,2,2,2,3,2
...,...,...,...,...,...,...,...,...,...
95,1,97,Я выбрал отрасль грузоперевозок. Целевая аудит...,2,2,4,3,1,2
96,1,98,Я выбрал отрасль ремонта техники. Целевая ауди...,3,2,3,2,2,2
97,1,99,Я выбрал отрасль такси. Целевая аудитория: вод...,1,1,4,3,1,2
98,1,100,Я выбрал отрасль ремонта квартир. Целевая ауди...,3,3,3,2,2,3
99,1,101,Я выбрал отрасль онлайн-магазинов. Целевая ауд...,4,4,4,3,1,3

In [3]:
df_test_cases

,Кейс,Решение,Решение кейса,ЦА,Проработка решения,Финансовая модель,Анализ рынков,Доказательства,Оценка
0,1,1,Я выбрал отрасль грузоперевозок для e-commerce...,5,3,3,5,4,4
1,1,2,Я выбрал отрасль салонов оптики и контактных л...,3,5,4,4,5,4
2,1,3,Я выбрал отрасль частных детских садов и центр...,3,3,5,3,2,3
3,1,4,Я выбрал отрасль цветочных магазинов и флорист...,3,3,3,3,5,3
4,1,5,Я выбрал отрасль салонов красоты (парикмахерск...,4,4,4,4,4,4
5,1,6,Я выбрал отрасль частных стоматологических кли...,5,3,3,3,3,3
6,1,7,Я выбрал отрасль доставки готовой еды (кухни н...,3,5,3,3,3,3
7,1,8,Я выбрал отрасль доставки цветов и подарков. Ц...,2,2,2,2,5,3
8,1,9,Я выбрал отрасль частных медицинских лаборатор...,3,2,3,3,3,3
9,1,10,Я выбрал отрасль частных стоматологических кли...,3,3,2,3,3,3
10,1,11,Я выбрал отрасль фитнес-клубов и студий группо...,2,2,2,1,2,2
11,1,12,Я выбрал отрасль салонов оптики и контактных л...,3,3,3,1,3,3
12,1,13,Я выбрал отрасль клининговых услуг для юридиче...,5,5,5,5,5,5
13,1,14,Я выбрал отрасль грузоперевозок и логистики дл...,5,4,5,5,5,5
14,1,15,Я выбрал отрасль частных детских садов и центр...,5,5,3,5,5,5
15,1,16,Я выбрал отрасль такси. Целевая аудитория — та...,1,1,1,1,2,1
16,1,17,Я выбрал отрасль строительства. Целевая аудито...,1,1,1,1,3,1
17,1,18,Я выбрал отрасль такси. Целевая аудитория — та...,1,1,1,1,4,2
18,1,19,Я выбрал отрасль доставки еды. Целевая аудитор...,1,3,1,1,1,1
19,1,20,Я выбрал отрасль пекарен и кондитерских. Целев...,2,5,2,2,2,3
20,1,21,Я выбрал отрасль частных стоматологических кли...,5,3,3,3,3,3
21,1,22,Я выбрал отрасль доставки готовой еды. ЦА — ма...,3,5,3,3,3,3
22,1,23,Я выбрал отрасль автомоек и детейлинга. ЦА — а...,3,3,5,3,3,3
23,1,24,Я выбрал отрасль такси и каршеринга. ЦА — такс...,3,3,3,5,3,3
24,1,25,Я выбрал отрасль доставки цветов. ЦА — цветочн...,2,2,2,2,4,2
25,1,26,Я выбрал отрасль салонов оптики. ЦА разделена ...,3,3,3,1,3,3
26,1,27,Я выбрал отрасль грузоперевозок для e-commerce...,5,1,1,1,1,2
27,1,28,Я выбрал отрасль пекарен. ЦА — пекарни. Им нуж...,1,5,1,1,1,2
28,1,29,Я выбрал отрасль автомоек. ЦА — автомойки. Им ...,1,1,5,1,1,2
29,1,30,Я выбрал отрасль клининга для юрлиц. Рынок 450...,5,5,5,5,1,4

In [4]:
df["Оценка"].value_counts()

Оценка
3    70
4    68
2    42
1    39
5    30
Name: count, dtype: Int64

In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import Pipeline
import pickle

In [7]:
y_audience = df['ЦА'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_audience, X_test_text_audience, y_train_audience, y_test_audience = train_test_split(
    X_text, y_audience, test_size=0.2, random_state=42
)
tfidf_audience = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_audience = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_audience = tfidf_audience.fit_transform(X_train_text_audience)
X_train_svd_audience = svd_audience.fit_transform(X_train_tfidf_audience)
X_test_tfidf_audience = tfidf_audience.transform(X_test_text_audience)
X_test_svd_audience = svd_audience.transform(X_test_tfidf_audience)

In [8]:
from sklearn.model_selection import GridSearchCV

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.svm import LinearSVC

In [17]:
param_grid = {
    'C': [0.1, 1, 10, 100],
    'max_iter': [1000, 2000]
}

In [18]:
grid_search_audience = GridSearchCV(LinearSVC(random_state=42, dual='auto'), param_grid, cv=5, scoring='accuracy')
grid_search_audience.fit(X_train_svd_audience, y_train_audience)
y_pred_audience = grid_search_audience.predict(X_test_svd_audience)
y_pred_audience

/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

array([1, 1, 3, 4, 3, 5, 3, 5, 3, 3, 5, 5, 3, 2, 5, 4, 3, 5, 5, 5, 5, 1,
       4, 5, 5, 1, 5, 1, 3, 4, 5, 5, 5, 5, 5, 3, 5, 5, 1, 5, 3, 3, 3, 2,
       3, 5, 5, 3, 1, 5])

In [19]:
y_sol= df['Проработка решения'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_sol, X_test_text_sol, y_train_sol, y_test_sol = train_test_split(
    X_text, y_sol, test_size=0.2, random_state=42
)
tfidf_sol = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_sol = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_sol = tfidf_sol.fit_transform(X_train_text_sol)
X_train_svd_sol = svd_sol.fit_transform(X_train_tfidf_sol)
X_test_tfidf_sol = tfidf_sol.transform(X_test_text_sol)
X_test_svd_sol = svd_sol.transform(X_test_tfidf_sol)

In [20]:
grid_search_sol = GridSearchCV(LinearSVC(random_state=42, dual='auto'), param_grid, cv=5, scoring='accuracy')
grid_search_sol.fit(X_train_svd_sol, y_train_sol)
y_pred_sol = grid_search_sol.predict(X_test_svd_sol)
y_pred_sol

/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

array([1, 1, 4, 5, 3, 5, 2, 5, 3, 3, 5, 5, 3, 2, 5, 3, 3, 5, 5, 4, 4, 1,
       4, 4, 4, 1, 1, 5, 2, 4, 4, 5, 5, 5, 5, 3, 5, 4, 1, 5, 3, 3, 3, 2,
       4, 5, 4, 4, 1, 5])

In [21]:
y_finance= df['Финансовая модель и метрики'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_finance, X_test_text_finance,y_train_finance, y_test_finance = train_test_split(
    X_text, y_finance, test_size=0.2, random_state=42
)
tfidf_finance = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_finance = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_finance = tfidf_finance.fit_transform(X_train_text_finance)
X_train_svd_finance = svd_finance.fit_transform(X_train_tfidf_finance)
X_test_tfidf_finance = tfidf_finance.transform(X_test_text_finance)
X_test_svd_finance = svd_finance.transform(X_test_tfidf_finance)

In [23]:
grid_search_finance = GridSearchCV(LinearSVC(random_state=42, dual='auto'), param_grid, cv=5, scoring='accuracy')
grid_search_finance.fit(X_train_svd_finance, y_train_finance)
y_pred_finance = grid_search_finance.predict(X_test_svd_finance)
y_pred_finance

/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

array([1, 1, 4, 4, 3, 1, 3, 4, 3, 3, 4, 4, 3, 2, 2, 3, 4, 5, 3, 2, 4, 1,
       4, 2, 2, 1, 2, 2, 2, 4, 2, 4, 5, 2, 2, 4, 5, 3, 1, 2, 3, 3, 3, 2,
       4, 5, 2, 3, 2, 4])

In [24]:
y_risks= df['Анализ рисков'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_risks, X_test_text_risks, y_train_risks, y_test_risks = train_test_split(
    X_text, y_risks, test_size=0.2, random_state=42
)
tfidf_risks = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_risks = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_risks = tfidf_risks.fit_transform(X_train_text_risks)
X_train_svd_risks = svd_risks.fit_transform(X_train_tfidf_risks)
X_test_tfidf_risks = tfidf_risks.transform(X_test_text_risks)
X_test_svd_risks = svd_risks.transform(X_test_tfidf_risks)

In [25]:
grid_search_risks = GridSearchCV(LinearSVC(random_state=42, dual='auto'), param_grid, cv=5, scoring='accuracy')
grid_search_risks.fit(X_train_svd_risks, y_train_risks)
y_pred_risks = grid_search_risks.predict(X_test_svd_risks)
y_pred_risks

/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

array([1, 1, 3, 4, 2, 1, 4, 4, 4, 2, 3, 4, 3, 1, 4, 4, 3, 5, 1, 1, 4, 1,
       2, 4, 1, 1, 1, 3, 2, 3, 3, 4, 5, 1, 1, 3, 5, 3, 1, 1, 3, 2, 2, 1,
       3, 5, 3, 3, 1, 4])

In [26]:
y_proves= df['Доказательства'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_proves, X_test_text_proves, y_train_proves, y_test_proves = train_test_split(
    X_text, y_proves, test_size=0.2, random_state=42
)
tfidf_proves = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_proves= TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_proves = tfidf_proves.fit_transform(X_train_text_proves)
X_train_svd_proves = svd_proves.fit_transform(X_train_tfidf_proves)
X_test_tfidf_proves = tfidf_proves.transform(X_test_text_proves)
X_test_svd_proves = svd_proves.transform(X_test_tfidf_proves)

In [27]:
grid_search_proves = GridSearchCV(LinearSVC(random_state=42, dual='auto'), param_grid, cv=5, scoring='accuracy')
grid_search_proves.fit(X_train_svd_proves, y_train_proves)
y_pred_proves = grid_search_proves.predict(X_test_svd_proves)
y_pred_proves

/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

array([1, 1, 1, 2, 2, 1, 4, 5, 3, 2, 4, 5, 4, 1, 5, 4, 4, 5, 5, 2, 4, 1,
       2, 5, 5, 1, 4, 3, 2, 3, 4, 4, 5, 5, 1, 2, 5, 4, 1, 5, 2, 2, 2, 1,
       4, 5, 4, 2, 1, 4])

In [28]:
new_results_df = pd.DataFrame(columns=['Id','Текст_решения','Анализ ЦА','Проработка решения','Финансовая модель и метрики','Анализ рынков','Доказательства','Предсказанная_оценка','Дата'])

In [29]:
import re

In [30]:
dec = '''МОЙ ПРОЕКТ

Я хочу сделать бота для школьников. Он будет помогать решать задачи.

Целевая аудитория - школьники. Им это нужно для учебы.

Мое решение - бот в телеграме. Он будет бесплатный. Похожих ботов нет.

Финансы: разработка стоит примерно 500 тысяч рублей. Потом будем зарабатывать на рекламе.

Риски: могут появиться конкуренты. Будем делать лучше.

Доказательства: я сам учился в школе и знаю, что это нужно. Многие мои друзья тоже так думают.'''

In [31]:
def get_prediction_audience(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_audience.transform([text])
  text_svd = svd_audience.transform(text_tfidf)
  score = grid_search_audience.predict(text_svd)[0]
  return int(score)

In [32]:
def get_prediction_solution(text):
  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_sol.transform([text])
  text_svd = svd_sol.transform(text_tfidf)
  score = grid_search_sol.predict(text_svd)[0]
  return int(score)

In [35]:
def get_prediction_finance(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_finance.transform([text])
  text_svd = svd_finance.transform(text_tfidf)
  score = grid_search_finance.predict(text_svd)[0]
  return int(score)

In [36]:
def get_prediction_risks(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_risks.transform([text])
  text_svd = svd_risks.transform(text_tfidf)
  score = grid_search_risks.predict(text_svd)[0]
  return int(score)

In [37]:
def get_prediction_proves(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_proves.transform([text])
  text_svd = svd_proves.transform(text_tfidf)
  score = grid_search_proves.predict(text_svd)[0]
  return int(score)

In [38]:
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix,
    cohen_kappa_score
)

In [39]:
df_test_cases['pred_audience'] = df_test_cases['Решение кейса'].apply(get_prediction_audience)
df_test_cases['pred_sol'] = df_test_cases['Решение кейса'].apply(get_prediction_solution)
df_test_cases['pred_finance'] = df_test_cases['Решение кейса'].apply(get_prediction_finance)
df_test_cases['pred_risks'] = df_test_cases['Решение кейса'].apply(get_prediction_risks)
df_test_cases['pred_proves'] = df_test_cases['Решение кейса'].apply(get_prediction_proves)

In [40]:
#ЦА
accuracy_audience = accuracy_score(df_test_cases['ЦА'], df_test_cases['pred_audience'])
f1micro_audience = f1_score(df_test_cases['ЦА'], df_test_cases['pred_audience'], average='micro')
f1macro_audience = f1_score(df_test_cases['ЦА'], df_test_cases['pred_audience'], average='macro')
print('accuracy_audience= ', accuracy_audience)
print('f1micro_audience= ', f1micro_audience)
print('f1macro_audience= ', f1macro_audience)

accuracy_audience=  0.6
f1micro_audience=  0.6
f1macro_audience=  0.48045112781954885

In [41]:
accuracy_sol = accuracy_score(df_test_cases['Проработка решения'], df_test_cases['pred_sol'])
f1micro_sol = f1_score(df_test_cases['Проработка решения'], df_test_cases['pred_sol'], average='micro')
f1macro_sol = f1_score(df_test_cases['Проработка решения'], df_test_cases['pred_sol'], average='macro')
print('accuracy_sol= ', accuracy_sol)
print('f1micro_sol= ', f1micro_sol)
print('f1macro_sol= ', f1macro_sol)

accuracy_sol=  0.36666666666666664
f1micro_sol=  0.36666666666666664
f1macro_sol=  0.2845676063067367

In [42]:
accuracy_finance = accuracy_score(df_test_cases['Финансовая модель'], df_test_cases['pred_finance'])
f1micro_finance = f1_score(df_test_cases['Финансовая модель'], df_test_cases['pred_finance'], average='micro')
f1macro_finance = f1_score(df_test_cases['Финансовая модель'], df_test_cases['pred_finance'], average='macro')
print('accuracy_finance= ', accuracy_finance)
print('f1micro_finance= ', f1micro_finance)
print('f1macro_finance= ', f1macro_finance)

accuracy_finance=  0.4
f1micro_finance=  0.4
f1macro_finance=  0.383777625882889

In [43]:
accuracy_risks = accuracy_score(df_test_cases['Анализ рынков'], df_test_cases['pred_risks'])
f1micro_risks = f1_score(df_test_cases['Анализ рынков'], df_test_cases['pred_risks'], average='micro')
f1macro_risks = f1_score(df_test_cases['Анализ рынков'], df_test_cases['pred_risks'], average='macro')
print('accuracy_risks= ', accuracy_risks)
print('f1micro_risks= ', f1micro_risks)
print('f1macro_risks= ', f1macro_risks)

accuracy_risks=  0.3333333333333333
f1micro_risks=  0.3333333333333333
f1macro_risks=  0.22293995859213248

In [44]:
accuracy_proves = accuracy_score(df_test_cases['Доказательства'], df_test_cases['pred_proves'])
f1micro_proves = f1_score(df_test_cases['Доказательства'], df_test_cases['pred_proves'], average='micro')
f1macro_proves = f1_score(df_test_cases['Доказательства'], df_test_cases['pred_proves'], average='macro')
print('accuracy_proves= ', accuracy_proves)
print('f1micro_proves= ', f1micro_proves)
print('f1macro_proves= ', f1macro_proves)

accuracy_proves=  0.26666666666666666
f1micro_proves=  0.26666666666666666
f1macro_proves=  0.23137254901960783

In [45]:
sec_dec = """АНАЛИЗ ЦА:
Выделено 3 сегмента:
- Школьники 10-11 класс (45%)
- Студенты (35%)
- Учителя (20%)
Проведен опрос 100 человек.

РЕШЕНИЕ:
Экосистема из 2 продуктов: телеграм бот + дашборд для учителей.
Партнеры: Яндекс.Образование, МФТИ.

ФИНАНСЫ:
CAPEX: 2 млн руб. CAC = 100 руб, LTV = 2000 руб.
Окупаемость: 10 месяцев.

РИСКИ:
Технические (30%) - резервный сервер.

ДОКАЗАТЕЛЬСТВА:
Пилот в школе: NPS = 65.
"""

In [46]:
sol_test = """ Я выбрала отрасль кофеен и кофе-точек с собой (кофе на вынос, кофейные киоски, небольшие кофейни на 2–5 столиков). ЦА разделена на две группы. Первая группа — это микробизнес: кофе-байки и кофе-островки с одним сотрудником, работают как ИП или самозанятые. Их проблема в том, что кофейные зерна нужно покупать свежей обжарки каждую неделю, а хорошие обжарщики требуют предоплату 100% за партию от 5 кг, это около 20–30 тысяч рублей единовременно, что для маленькой точки с ежедневной выручкой 5–7 тысяч рублей чувствительно. Вторая группа — это малый бизнес: кофейни с посадочными местами и штатом 2–5 бариста. Их проблема в том, что сезонность спроса сильно различается: зимой продажи выше за счет горячих напитков, а летом люди покупают холодный кофе и чаще берут с собой, но в межсезонье (апрель и октябрь) падение выручки достигает 30%, при этом аренду и зарплату платить надо. Я опиралась на данные исследования «Рынок кофеен России 2024» от компании CoffeeData: рост рынка на 15% за год, количество кофеен достигло 12 тысяч, из них 70% — малый и микробизнес. Также я посмотрел открытую статистику по кофейному рынку на сайте Росстата и несколько статей в профильных телеграм-каналах. В качестве решения я предлагаю продукт «Альфа.Кофе»: кредит на закупку зёрен с отсрочкой первого платежа на 30 дней и с льготным периодом 0% на первые две недели, а также сезонный овердрафт на покрытие аренды в межсезонье на сумму до 100 тысяч рублей. Партнеры — два крупных обжарщика зерна «Coffe Lab» и «Torrefacto», с которыми можно договориться о более выгодных ценах для клиентов банка. Отличие от конкурентов в том, что ни у Сбера, ни у Т-Банка нет специального продукта для кофеен с отсрочкой именно под зерно. По финансам: разработка кредитного продукта обойдется примерно в 6 миллионов рублей, интеграция с партнерами-обжарщиками — в 2 миллиона, маркетинг в кофейных чатах и через конференции бариста — в 2 миллиона. Прогноз: 350 клиентов в первый год, средний доход с клиента — 20 тысяч рублей (за счет процентов по кредиту и эквайринга), выручка — 7 миллионов рублей. Окупаемость — примерно 2,5 года. Риски: конкурентный — другие банки могут запустить похожие продукты; кредитный — часть клиентов может не вернуть деньги, но мы будем проверять по выписке с кофемашины, кто сколько продает. В доказательство я использовал данные CoffeeData и результаты пары интервью с владельцами кофеен в своем городе."""

In [47]:
predicted_score_audience = get_prediction_audience(sec_dec)
predicted_score_sol = get_prediction_solution(sec_dec)
predicted_score_finance = get_prediction_finance(sec_dec)
predicted_score_risks = get_prediction_risks(sec_dec)
predicted_score_proves = get_prediction_proves(sec_dec)
predicted_score_audience2 = get_prediction_audience(sec_dec)
predicted_score_sol2 = get_prediction_solution(sec_dec)
predicted_score_finance2 = get_prediction_finance(sec_dec)
predicted_score_risks2 = get_prediction_risks(sec_dec)
predicted_score_proves2 = get_prediction_proves(sec_dec)
new_row = pd.DataFrame([{
    'Id': 1,
    'Текст_решения': dec,
    'Анализ ЦА': predicted_score_audience,
    'Проработка решения': predicted_score_sol,
    'Финансовая модель и метрики': predicted_score_finance,
    'Анализ рынков': predicted_score_risks,
    'Доказательства': predicted_score_proves,
    'Предсказанная_оценка': round((predicted_score_audience + predicted_score_sol +
                      predicted_score_finance + predicted_score_risks +
                      predicted_score_proves) / 5),
    'Дата': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
}])
new_row2 = pd.DataFrame([{
    'Id': 1,
    'Текст_решения': dec,
    'Анализ ЦА': predicted_score_audience2,
    'Проработка решения': predicted_score_sol2,
    'Финансовая модель и метрики': predicted_score_finance2,
    'Анализ рынков': predicted_score_risks2,
    'Доказательства': predicted_score_proves2,
    'Предсказанная_оценка': round((predicted_score_audience2 + predicted_score_sol2 +
                      predicted_score_finance2 + predicted_score_risks2 +
                      predicted_score_proves2) / 5),
    'Дата': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
}])
new_results_df = pd.concat([new_results_df, new_row, new_row2], ignore_index=True)
new_results_df.to_excel("новая_таблица.xlsx", index=False)

In [48]:
new_results_df

,Id,Текст_решения,Анализ ЦА,Проработка решения,Финансовая модель и метрики,Анализ рынков,Доказательства,Предсказанная_оценка,Дата
0,1,МОЙ ПРОЕКТ\n\nЯ хочу сделать бота для школьник...,5,5,4,4,5,5,2026-06-27 14:48:09
1,1,МОЙ ПРОЕКТ\n\nЯ хочу сделать бота для школьник...,5,5,4,4,5,5,2026-06-27 14:48:09