In [2]:
import pandas as pd
import numpy as np
df = pd.read_excel(r"/content/cases_train2 (6) (1) (1).xlsx")
df_test_cases = pd.read_excel(r"/content/Test1_2 (3).xlsx")
df['Оценка'] = df['Оценка'].round().astype('Int64')
df_test_cases['Оценка'] = df_test_cases['Оценка'].round().astype('Int64')
#df = pd.read_excel("/content/good table.xlsx")
df.head(100)

,Кейс,Решение,Решение кейса,ЦА,Проработка решения,Финансовая модель и метрики,Анализ рисков,Доказательства,Оценка
0,1,1,Я выбрал отрасль туризма и гостиничного бизнес...,1,1,1,1,1,1
1,1,2,Я выбрал для разработки отраслевого решения сф...,2,2,2,2,2,2
2,1,4,"Я выбрал отрасль образования, а именно сегмент...",2,4,4,3,3,3
3,1,5,Я выбрал отрасль розничной торговли продуктами...,1,3,2,2,1,2
4,1,6,Я выбрал для отраслевого решения сферу гостини...,3,2,2,2,3,2
...,...,...,...,...,...,...,...,...,...
95,1,97,Я выбрал отрасль грузоперевозок. Целевая аудит...,2,2,4,3,1,2
96,1,98,Я выбрал отрасль ремонта техники. Целевая ауди...,3,2,3,2,2,2
97,1,99,Я выбрал отрасль такси. Целевая аудитория: вод...,1,1,4,3,1,2
98,1,100,Я выбрал отрасль ремонта квартир. Целевая ауди...,3,3,3,2,2,3
99,1,101,Я выбрал отрасль онлайн-магазинов. Целевая ауд...,4,4,4,3,1,3

In [3]:
df_test_cases

,Кейс,Решение,Решение кейса,ЦА,Проработка решения,Финансовая модель,Анализ рынков,Доказательства,Оценка
0,1,1,Я выбрал отрасль грузоперевозок для e-commerce...,5,3,3,5,4,4
1,1,2,Я выбрал отрасль салонов оптики и контактных л...,3,5,4,4,5,4
2,1,3,Я выбрал отрасль частных детских садов и центр...,3,3,5,3,2,3
3,1,4,Я выбрал отрасль цветочных магазинов и флорист...,3,3,3,3,5,3
4,1,5,Я выбрал отрасль салонов красоты (парикмахерск...,4,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...
125,1,126,Я выбрал отрасль частных фотостудий. ЦА практи...,1,5,3,4,3,3
126,1,127,Я выбрал отрасль частных школ программирования...,5,3,4,3,5,4
127,1,128,Я выбрал отрасль небольших клининговых компани...,2,2,5,4,2,3
128,1,129,Я выбрал отрасль частных диагностических лабор...,5,5,3,4,5,4
129,1,130,Я выбрал отрасль небольших транспортных компан...,3,4,2,5,4,3

In [4]:
df["Оценка"].value_counts()

Оценка
4     208
3     206
1     110
2     105
5      94
7      26
6      21
8      21
9      18
10      6
Name: count, dtype: Int64

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import Pipeline
import pickle

In [6]:
from sklearn.metrics import classification_report

In [7]:
y_audience = df['ЦА'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_audience, X_test_text_audience, y_train_audience, y_test_audience = train_test_split(
    X_text, y_audience, test_size=0.2, random_state=42
)
tfidf_audience = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
X_train_tfidf_audience = tfidf_audience.fit_transform(X_train_text_audience)
#X_train_svd_audience = svd_audience.fit_transform(X_train_tfidf_audience)
X_test_tfidf_audience = tfidf_audience.transform(X_test_text_audience)
#X_test_svd_audience = svd_audience.transform(X_test_tfidf_audience)

In [8]:
from sklearn.model_selection import GridSearchCV

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.svm import LinearSVC

In [10]:
param_grid = {
    'C': [0.1, 1, 10, 100],
    'max_iter': [1000, 2000]
}

In [11]:
grid_search_audience = LinearSVC(random_state=42, C=1, max_iter=1000, dual=False)
grid_search_audience.fit(X_train_tfidf_audience, y_train_audience)
y_pred_audience = grid_search_audience.predict(X_test_tfidf_audience)
print(classification_report(y_test_audience, y_pred_audience))
print("MAE=", mean_absolute_error(y_test_audience, y_pred_audience))
#y_pred_audience

              precision    recall  f1-score   support

           1       0.64      0.69      0.67        13
           2       0.54      0.32      0.40        22
           3       0.50      0.56      0.53        34
           4       0.54      0.48      0.51        52
           5       0.50      0.75      0.60        32
           6       0.50      0.50      0.50         2
           7       0.00      0.00      0.00         3
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         4

    accuracy                           0.52       163
   macro avg       0.36      0.37      0.36       163
weighted avg       0.51      0.52      0.50       163

MAE= 0.7116564417177914

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [12]:
y_sol= df['Проработка решения'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_sol, X_test_text_sol, y_train_sol, y_test_sol = train_test_split(
    X_text, y_sol, test_size=0.2, random_state=42
)
tfidf_sol = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
#svd_sol = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_sol = tfidf_sol.fit_transform(X_train_text_sol)
#X_train_svd_sol = svd_sol.fit_transform(X_train_tfidf_sol)
X_test_tfidf_sol = tfidf_sol.transform(X_test_text_sol)
#X_test_svd_sol = svd_sol.transform(X_test_tfidf_sol)

In [13]:
grid_search_sol = LinearSVC(random_state=42, C=1, max_iter=1000, dual=False)
grid_search_sol.fit(X_train_tfidf_sol, y_train_sol)
y_pred_sol = grid_search_sol.predict(X_test_tfidf_sol)
#y_pred_sol
print(classification_report(y_test_sol, y_pred_sol))
print("MAE=", mean_absolute_error(y_test_sol, y_pred_sol))

              precision    recall  f1-score   support

           1       0.65      0.73      0.69        15
           2       0.29      0.21      0.24        24
           3       0.44      0.55      0.49        31
           4       0.60      0.52      0.56        46
           5       0.50      0.62      0.55        37
           6       0.00      0.00      0.00         2
           7       0.50      0.25      0.33         4
           8       0.00      0.00      0.00         2
           9       0.00      0.00      0.00         2

    accuracy                           0.50       163
   macro avg       0.33      0.32      0.32       163
weighted avg       0.48      0.50      0.48       163

MAE= 0.8098159509202454

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [14]:
y_finance= df['Финансовая модель и метрики'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_finance, X_test_text_finance,y_train_finance, y_test_finance = train_test_split(
    X_text, y_finance, test_size=0.2, random_state=42
)
tfidf_finance = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
#svd_finance = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_finance = tfidf_finance.fit_transform(X_train_text_finance)
#X_train_svd_finance = svd_finance.fit_transform(X_train_tfidf_finance)
X_test_tfidf_finance = tfidf_finance.transform(X_test_text_finance)
#X_test_svd_finance = svd_finance.transform(X_test_tfidf_finance)

In [15]:
grid_search_finance = LinearSVC(random_state=42, C=1, max_iter=1000, dual=False)
grid_search_finance.fit(X_train_tfidf_finance, y_train_finance)
y_pred_finance = grid_search_finance.predict(X_test_tfidf_finance)
print(classification_report(y_test_finance, y_pred_finance))
print("MAE=", mean_absolute_error(y_test_finance, y_pred_finance))

              precision    recall  f1-score   support

           1       0.62      0.83      0.71        12
           2       0.42      0.38      0.40        29
           3       0.49      0.49      0.49        37
           4       0.54      0.54      0.54        50
           5       0.48      0.62      0.54        26
           6       0.00      0.00      0.00         3
           7       0.00      0.00      0.00         2
           8       0.00      0.00      0.00         2
           9       0.00      0.00      0.00         2

    accuracy                           0.50       163
   macro avg       0.28      0.32      0.30       163
weighted avg       0.47      0.50      0.49       163

MAE= 0.7116564417177914

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [16]:
y_risks= df['Анализ рисков'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_risks, X_test_text_risks, y_train_risks, y_test_risks = train_test_split(
    X_text, y_risks, test_size=0.2, random_state=42
)
tfidf_risks = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
#svd_risks = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_risks = tfidf_risks.fit_transform(X_train_text_risks)
#X_train_svd_risks = svd_risks.fit_transform(X_train_tfidf_risks)
X_test_tfidf_risks = tfidf_risks.transform(X_test_text_risks)
#X_test_svd_risks = svd_risks.transform(X_test_tfidf_risks)

In [17]:
grid_search_risks = LinearSVC(random_state=42, C=1, max_iter=1000, dual=False)
grid_search_risks.fit(X_train_tfidf_risks, y_train_risks)
y_pred_risks = grid_search_risks.predict(X_test_tfidf_risks)
print(classification_report(y_test_risks, y_pred_risks))
print("MAE=", mean_absolute_error(y_test_risks, y_pred_risks))

              precision    recall  f1-score   support

           1       0.65      0.65      0.65        20
           2       0.33      0.22      0.27        27
           3       0.56      0.64      0.59        47
           4       0.40      0.59      0.48        32
           5       0.50      0.39      0.44        28
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         3
           8       1.00      0.67      0.80         3
           9       0.00      0.00      0.00         1

    accuracy                           0.50       163
   macro avg       0.38      0.35      0.36       163
weighted avg       0.48      0.50      0.48       163

MAE= 0.7055214723926381

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [18]:
y_proves= df['Доказательства'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_proves, X_test_text_proves, y_train_proves, y_test_proves = train_test_split(
    X_text, y_proves, test_size=0.2, random_state=42
)
tfidf_proves = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
#svd_proves= TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_proves = tfidf_proves.fit_transform(X_train_text_proves)
#X_train_svd_proves = svd_proves.fit_transform(X_train_tfidf_proves)
X_test_tfidf_proves = tfidf_proves.transform(X_test_text_proves)
#X_test_svd_proves = svd_proves.transform(X_test_tfidf_proves)

In [19]:
grid_search_proves = LinearSVC(random_state=42, C=1, max_iter=1000, dual=False)
grid_search_proves.fit(X_train_tfidf_proves, y_train_proves)
y_pred_proves = grid_search_proves.predict(X_test_tfidf_proves)
print(classification_report(y_test_proves, y_pred_proves))
print("MAE=", mean_absolute_error(y_test_proves, y_pred_proves))

              precision    recall  f1-score   support

           1       0.82      0.67      0.73        27
           2       0.38      0.36      0.37        22
           3       0.39      0.24      0.30        37
           4       0.42      0.55      0.48        40
           5       0.43      0.68      0.53        28
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         3
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         3

    accuracy                           0.47       163
   macro avg       0.27      0.28      0.27       163
weighted avg       0.45      0.47      0.45       163

MAE= 0.754601226993865

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
new_results_df = pd.DataFrame(columns=['Id','Текст_решения','Анализ ЦА','Проработка решения','Финансовая модель и метрики','Анализ рынков','Доказательства','Предсказанная_оценка','Дата'])

In [ ]:
new_results_df

Empty DataFrame
Columns: [Id, Текст_решения, Анализ ЦА, Проработка решения, Финансовая модель и метрики, Анализ рынков, Доказательства, Предсказанная_оценка, Дата]
Index: []

In [ ]:
import re

In [ ]:
dec = '''МОЙ ПРОЕКТ

Я хочу сделать бота для школьников. Он будет помогать решать задачи.

Целевая аудитория - школьники. Им это нужно для учебы.

Мое решение - бот в телеграме. Он будет бесплатный. Похожих ботов нет.

Финансы: разработка стоит примерно 500 тысяч рублей. Потом будем зарабатывать на рекламе.

Риски: могут появиться конкуренты. Будем делать лучше.

Доказательства: я сам учился в школе и знаю, что это нужно. Многие мои друзья тоже так думают.'''

In [20]:
def get_prediction_audience(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_audience.transform([text])
  #text_svd = svd_audience.transform(text_tfidf)
  score = grid_search_audience.predict(text_tfidf)[0]
  return int(score)

In [21]:
def get_prediction_solution(text):
  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_sol.transform([text])
  #text_svd = svd_sol.transform(text_tfidf)
  score = grid_search_sol.predict(text_tfidf)[0]
  return int(score)

In [22]:
def get_prediction_finance(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_finance.transform([text])
  #text_svd = svd_finance.transform(text_tfidf)
  score = grid_search_finance.predict(text_tfidf)[0]
  return int(score)

In [23]:
def get_prediction_risks(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_risks.transform([text])
  #text_svd = svd_risks.transform(text_tfidf)
  score = grid_search_risks.predict(text_tfidf)[0]
  return int(score)

In [24]:
def get_prediction_proves(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_proves.transform([text])
  #text_svd = svd_proves.transform(text_tfidf)
  score = grid_search_proves.predict(text_tfidf)[0]
  return int(score)

In [25]:
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    mean_absolute_error,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix,
    cohen_kappa_score
)

In [26]:
df_test_cases['pred_audience'] = df_test_cases['Решение кейса'].apply(get_prediction_audience)
df_test_cases['pred_sol'] = df_test_cases['Решение кейса'].apply(get_prediction_solution)
df_test_cases['pred_finance'] = df_test_cases['Решение кейса'].apply(get_prediction_finance)
df_test_cases['pred_risks'] = df_test_cases['Решение кейса'].apply(get_prediction_risks)
df_test_cases['pred_proves'] = df_test_cases['Решение кейса'].apply(get_prediction_proves)

In [27]:
#ЦА
accuracy_audience = accuracy_score(df_test_cases['ЦА'], df_test_cases['pred_audience'])
f1micro_audience = f1_score(df_test_cases['ЦА'], df_test_cases['pred_audience'], average='micro')
f1macro_audience = f1_score(df_test_cases['ЦА'], df_test_cases['pred_audience'], average='macro')
print('accuracy_audience= ', accuracy_audience)
print('f1micro_audience= ', f1micro_audience)
print('f1macro_audience= ', f1macro_audience)
print(classification_report(df_test_cases['ЦА'], df_test_cases['pred_audience']))
print("MAE=", mean_absolute_error(df_test_cases['ЦА'], df_test_cases['pred_audience']))

accuracy_audience=  0.6076923076923076
f1micro_audience=  0.6076923076923076
f1macro_audience=  0.6034500489953527
              precision    recall  f1-score   support

           1       0.50      0.52      0.51        23
           2       0.60      0.58      0.59        26
           3       0.65      0.65      0.65        34
           4       0.62      0.59      0.60        22
           5       0.65      0.68      0.67        25

    accuracy                           0.61       130
   macro avg       0.60      0.60      0.60       130
weighted avg       0.61      0.61      0.61       130

MAE= 0.5384615384615384

In [28]:
accuracy_sol = accuracy_score(df_test_cases['Проработка решения'], df_test_cases['pred_sol'])
f1micro_sol = f1_score(df_test_cases['Проработка решения'], df_test_cases['pred_sol'], average='micro')
f1macro_sol = f1_score(df_test_cases['Проработка решения'], df_test_cases['pred_sol'], average='macro')
print('accuracy_sol= ', accuracy_sol)
print('f1micro_sol= ', f1micro_sol)
print('f1macro_sol= ', f1macro_sol)
print(classification_report(df_test_cases['Проработка решения'], df_test_cases['pred_sol']))
print("MAE=", mean_absolute_error(df_test_cases['Проработка решения'], df_test_cases['pred_sol']))

accuracy_sol=  0.5538461538461539
f1micro_sol=  0.5538461538461539
f1macro_sol=  0.5567568263567804
              precision    recall  f1-score   support

           1       0.62      0.76      0.68        21
           2       0.67      0.44      0.53        32
           3       0.52      0.53      0.52        30
           4       0.50      0.56      0.53        25
           5       0.50      0.55      0.52        22

    accuracy                           0.55       130
   macro avg       0.56      0.57      0.56       130
weighted avg       0.56      0.55      0.55       130

MAE= 0.5384615384615384

In [ ]:
df_test_cases

,Кейс,Решение,Решение кейса,ЦА,Проработка решения,Финансовая модель,Анализ рынков,Доказательства,Оценка,pred_audience,pred_sol,pred_finance,pred_risks,pred_proves,Predict_score
0,1,1,Я выбрал отрасль грузоперевозок для e-commerce...,5,3,3,5,4,4,5,5,4,2,5,4.0
1,1,2,Я выбрал отрасль салонов оптики и контактных л...,3,5,4,4,5,4,5,5,2,2,4,4.0
2,1,3,Я выбрал отрасль частных детских садов и центр...,3,3,5,3,2,3,5,4,4,4,5,4.0
3,1,4,Я выбрал отрасль цветочных магазинов и флорист...,3,3,3,3,5,3,3,4,2,2,2,3.0
4,1,5,Я выбрал отрасль салонов красоты (парикмахерск...,4,4,4,4,4,4,4,4,3,3,4,4.0
5,1,6,Я выбрал отрасль частных стоматологических кли...,5,3,3,3,3,3,5,5,1,4,5,4.0
6,1,7,Я выбрал отрасль доставки готовой еды (кухни н...,3,5,3,3,3,3,1,5,4,2,1,3.0
7,1,8,Я выбрал отрасль доставки цветов и подарков. Ц...,2,2,2,2,5,3,1,1,2,1,5,2.0
8,1,9,Я выбрал отрасль частных медицинских лаборатор...,3,2,3,3,3,3,3,5,3,4,2,3.0
9,1,10,Я выбрал отрасль частных стоматологических кли...,3,3,2,3,3,3,5,4,4,2,2,3.0
10,1,11,Я выбрал отрасль фитнес-клубов и студий группо...,2,2,2,1,2,2,1,1,1,1,1,1.0
11,1,12,Я выбрал отрасль салонов оптики и контактных л...,3,3,3,1,3,3,3,4,4,2,2,3.0
12,1,13,Я выбрал отрасль клининговых услуг для юридиче...,5,5,5,5,5,5,5,4,4,4,5,4.0
13,1,14,Я выбрал отрасль грузоперевозок и логистики дл...,5,4,5,5,5,5,5,5,4,4,5,5.0
14,1,15,Я выбрал отрасль частных детских садов и центр...,5,5,3,5,5,5,5,4,4,4,5,4.0
15,1,16,Я выбрал отрасль такси. Целевая аудитория — та...,1,1,1,1,2,1,1,1,1,1,1,1.0
16,1,17,Я выбрал отрасль строительства. Целевая аудито...,1,1,1,1,3,1,1,1,1,1,1,1.0
17,1,18,Я выбрал отрасль такси. Целевая аудитория — та...,1,1,1,1,4,2,1,1,1,1,1,1.0
18,1,19,Я выбрал отрасль доставки еды. Целевая аудитор...,1,3,1,1,1,1,1,1,1,1,1,1.0
19,1,20,Я выбрал отрасль пекарен и кондитерских. Целев...,2,5,2,2,2,3,1,5,2,2,1,2.0
20,1,21,Я выбрал отрасль частных стоматологических кли...,5,3,3,3,3,3,5,5,5,5,5,5.0
21,1,22,Я выбрал отрасль доставки готовой еды. ЦА — ма...,3,5,3,3,3,3,4,5,4,2,1,3.0
22,1,23,Я выбрал отрасль автомоек и детейлинга. ЦА — а...,3,3,5,3,3,3,1,2,5,1,1,2.0
23,1,24,Я выбрал отрасль такси и каршеринга. ЦА — такс...,3,3,3,5,3,3,1,1,1,5,1,2.0
24,1,25,Я выбрал отрасль доставки цветов. ЦА — цветочн...,2,2,2,2,4,2,1,1,2,1,2,1.0
25,1,26,Я выбрал отрасль салонов оптики. ЦА разделена ...,3,3,3,1,3,3,5,5,2,2,5,4.0
26,1,27,Я выбрал отрасль грузоперевозок для e-commerce...,5,1,1,1,1,2,5,5,1,1,5,3.0
27,1,28,Я выбрал отрасль пекарен. ЦА — пекарни. Им нуж...,1,5,1,1,1,2,1,5,2,2,1,2.0
28,1,29,Я выбрал отрасль автомоек. ЦА — автомойки. Им ...,1,1,5,1,1,2,1,1,5,1,1,2.0
29,1,30,Я выбрал отрасль клининга для юрлиц. Рынок 450...,5,5,5,5,1,4,5,5,5,5,5,5.0

In [29]:
accuracy_finance = accuracy_score(df_test_cases['Финансовая модель'], df_test_cases['pred_finance'])
f1micro_finance = f1_score(df_test_cases['Финансовая модель'], df_test_cases['pred_finance'], average='micro')
f1macro_finance = f1_score(df_test_cases['Финансовая модель'], df_test_cases['pred_finance'], average='macro')
print('accuracy_finance= ', accuracy_finance)
print('f1micro_finance= ', f1micro_finance)
print('f1macro_finance= ', f1macro_finance)
print(classification_report(df_test_cases['Финансовая модель'], df_test_cases['pred_finance']))
print("MAE=", mean_absolute_error(df_test_cases['Финансовая модель'], df_test_cases['pred_finance']))

accuracy_finance=  0.5692307692307692
f1micro_finance=  0.5692307692307692
f1macro_finance=  0.5784096480047063
              precision    recall  f1-score   support

           1       0.57      0.91      0.70        23
           2       0.68      0.39      0.50        33
           3       0.46      0.58      0.51        31
           4       0.48      0.46      0.47        24
           5       0.92      0.58      0.71        19

    accuracy                           0.57       130
   macro avg       0.62      0.58      0.58       130
weighted avg       0.61      0.57      0.56       130

MAE= 0.5307692307692308

In [30]:
accuracy_risks = accuracy_score(df_test_cases['Анализ рынков'], df_test_cases['pred_risks'])
f1micro_risks = f1_score(df_test_cases['Анализ рынков'], df_test_cases['pred_risks'], average='micro')
f1macro_risks = f1_score(df_test_cases['Анализ рынков'], df_test_cases['pred_risks'], average='macro')
print('accuracy_risks= ', accuracy_risks)
print('f1micro_risks= ', f1micro_risks)
print('f1macro_risks= ', f1macro_risks)
print(classification_report(df_test_cases['Анализ рынков'], df_test_cases['pred_risks']))
print("MAE=", mean_absolute_error(df_test_cases['Анализ рынков'], df_test_cases['pred_risks']))

accuracy_risks=  0.4461538461538462
f1micro_risks=  0.4461538461538462
f1macro_risks=  0.40123891174738635
              precision    recall  f1-score   support

           1       0.58      0.73      0.64        26
           2       0.52      0.38      0.44        32
           3       0.31      0.37      0.34        30
           4       0.42      0.56      0.48        27
           5       0.33      0.07      0.11        15

    accuracy                           0.45       130
   macro avg       0.43      0.42      0.40       130
weighted avg       0.44      0.45      0.43       130

MAE= 0.7538461538461538

In [31]:
accuracy_proves = accuracy_score(df_test_cases['Доказательства'], df_test_cases['pred_proves'])
f1micro_proves = f1_score(df_test_cases['Доказательства'], df_test_cases['pred_proves'], average='micro')
f1macro_proves = f1_score(df_test_cases['Доказательства'], df_test_cases['pred_proves'], average='macro')
print('accuracy_proves= ', accuracy_proves)
print('f1micro_proves= ', f1micro_proves)
print('f1macro_proves= ', f1macro_proves)
print(classification_report(df_test_cases['Доказательства'], df_test_cases['pred_proves']))
print("MAE=", mean_absolute_error(df_test_cases['Доказательства'], df_test_cases['pred_proves']))

accuracy_proves=  0.5923076923076923
f1micro_proves=  0.5923076923076923
f1macro_proves=  0.5743186582809223
              precision    recall  f1-score   support

           1       0.43      0.83      0.57        18
           2       0.68      0.61      0.64        38
           3       0.70      0.28      0.40        25
           4       0.57      0.63      0.60        19
           5       0.67      0.67      0.67        30

    accuracy                           0.59       130
   macro avg       0.61      0.60      0.57       130
weighted avg       0.63      0.59      0.58       130

MAE= 0.6461538461538462

In [32]:
df_test_cases["Predict_score"] = round((df_test_cases['pred_audience'] + df_test_cases['pred_sol'] + df_test_cases['pred_finance'] + df_test_cases['pred_risks'] + df_test_cases['pred_proves'])/5)

In [33]:
print("MAE= ",mean_absolute_error(df_test_cases["Оценка"], df_test_cases["Predict_score"]))

MAE=  0.43846153846153846

In [ ]:
sec_dec = """АНАЛИЗ ЦА:
Выделено 3 сегмента:
- Школьники 10-11 класс (45%)
- Студенты (35%)
- Учителя (20%)
Проведен опрос 100 человек.

РЕШЕНИЕ:
Экосистема из 2 продуктов: телеграм бот + дашборд для учителей.
Партнеры: Яндекс.Образование, МФТИ.

ФИНАНСЫ:
CAPEX: 2 млн руб. CAC = 100 руб, LTV = 2000 руб.
Окупаемость: 10 месяцев.

РИСКИ:
Технические (30%) - резервный сервер.

ДОКАЗАТЕЛЬСТВА:
Пилот в школе: NPS = 65.
"""

In [ ]:
sol_test = """ Я выбрала отрасль кофеен и кофе-точек с собой (кофе на вынос, кофейные киоски, небольшие кофейни на 2–5 столиков). ЦА разделена на две группы. Первая группа — это микробизнес: кофе-байки и кофе-островки с одним сотрудником, работают как ИП или самозанятые. Их проблема в том, что кофейные зерна нужно покупать свежей обжарки каждую неделю, а хорошие обжарщики требуют предоплату 100% за партию от 5 кг, это около 20–30 тысяч рублей единовременно, что для маленькой точки с ежедневной выручкой 5–7 тысяч рублей чувствительно. Вторая группа — это малый бизнес: кофейни с посадочными местами и штатом 2–5 бариста. Их проблема в том, что сезонность спроса сильно различается: зимой продажи выше за счет горячих напитков, а летом люди покупают холодный кофе и чаще берут с собой, но в межсезонье (апрель и октябрь) падение выручки достигает 30%, при этом аренду и зарплату платить надо. Я опиралась на данные исследования «Рынок кофеен России 2024» от компании CoffeeData: рост рынка на 15% за год, количество кофеен достигло 12 тысяч, из них 70% — малый и микробизнес. Также я посмотрел открытую статистику по кофейному рынку на сайте Росстата и несколько статей в профильных телеграм-каналах. В качестве решения я предлагаю продукт «Альфа.Кофе»: кредит на закупку зёрен с отсрочкой первого платежа на 30 дней и с льготным периодом 0% на первые две недели, а также сезонный овердрафт на покрытие аренды в межсезонье на сумму до 100 тысяч рублей. Партнеры — два крупных обжарщика зерна «Coffe Lab» и «Torrefacto», с которыми можно договориться о более выгодных ценах для клиентов банка. Отличие от конкурентов в том, что ни у Сбера, ни у Т-Банка нет специального продукта для кофеен с отсрочкой именно под зерно. По финансам: разработка кредитного продукта обойдется примерно в 6 миллионов рублей, интеграция с партнерами-обжарщиками — в 2 миллиона, маркетинг в кофейных чатах и через конференции бариста — в 2 миллиона. Прогноз: 350 клиентов в первый год, средний доход с клиента — 20 тысяч рублей (за счет процентов по кредиту и эквайринга), выручка — 7 миллионов рублей. Окупаемость — примерно 2,5 года. Риски: конкурентный — другие банки могут запустить похожие продукты; кредитный — часть клиентов может не вернуть деньги, но мы будем проверять по выписке с кофемашины, кто сколько продает. В доказательство я использовал данные CoffeeData и результаты пары интервью с владельцами кофеен в своем городе."""

In [ ]:
predicted_score_audience = get_prediction_audience(sec_dec)
predicted_score_sol = get_prediction_solution(sec_dec)
predicted_score_finance = get_prediction_finance(sec_dec)
predicted_score_risks = get_prediction_risks(sec_dec)
predicted_score_proves = get_prediction_proves(sec_dec)
predicted_score_audience2 = get_prediction_audience(sec_dec)
predicted_score_sol2 = get_prediction_solution(sec_dec)
predicted_score_finance2 = get_prediction_finance(sec_dec)
predicted_score_risks2 = get_prediction_risks(sec_dec)
predicted_score_proves2 = get_prediction_proves(sec_dec)
new_row = pd.DataFrame([{
    'Id': 1,
    'Текст_решения': dec,
    'Анализ ЦА': predicted_score_audience,
    'Проработка решения': predicted_score_sol,
    'Финансовая модель и метрики': predicted_score_finance,
    'Анализ рынков': predicted_score_risks,
    'Доказательства': predicted_score_proves,
    'Предсказанная_оценка': round((predicted_score_audience + predicted_score_sol +
                      predicted_score_finance + predicted_score_risks +
                      predicted_score_proves) / 5),
    'Дата': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
}])
new_row2 = pd.DataFrame([{
    'Id': 1,
    'Текст_решения': dec,
    'Анализ ЦА': predicted_score_audience2,
    'Проработка решения': predicted_score_sol2,
    'Финансовая модель и метрики': predicted_score_finance2,
    'Анализ рынков': predicted_score_risks2,
    'Доказательства': predicted_score_proves2,
    'Предсказанная_оценка': round((predicted_score_audience2 + predicted_score_sol2 +
                      predicted_score_finance2 + predicted_score_risks2 +
                      predicted_score_proves2) / 5),
    'Дата': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
}])
new_results_df = pd.concat([new_results_df, new_row, new_row2], ignore_index=True)
new_results_df.to_excel("новая_таблица.xlsx", index=False)

In [ ]:
new_results_df

,Id,Текст_решения,Анализ ЦА,Проработка решения,Финансовая модель и метрики,Анализ рынков,Доказательства,Предсказанная_оценка,Дата
0,1,МОЙ ПРОЕКТ\n\nЯ хочу сделать бота для школьник...,5,5,4,4,5,5,2026-06-27 14:48:09
1,1,МОЙ ПРОЕКТ\n\nЯ хочу сделать бота для школьник...,5,5,4,4,5,5,2026-06-27 14:48:09