In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel('/content/cases_train2 (12).xlsx')
df['Оценка'] = df['Оценка'].round().astype('Int64')
df_test_cases = pd.read_excel('/content/Test1_2 (3).xlsx')
df_test_cases['Оценка'] = df_test_cases['Оценка'].round().astype('Int64')
#df = pd.read_excel("/content/good table.xlsx")
df.head(100)

,Кейс,Решение,Решение кейса,ЦА,Проработка решения,Финансовая модель и метрики,Анализ рисков,Доказательства,Оценка
0,1,1,Я выбрал отрасль туризма и гостиничного бизнес...,1,1,1,1,1,1
1,1,2,Я выбрал для разработки отраслевого решения сф...,2,2,2,2,2,2
2,1,4,"Я выбрал отрасль образования, а именно сегмент...",2,4,4,3,3,3
3,1,5,Я выбрал отрасль розничной торговли продуктами...,1,3,2,2,1,2
4,1,6,Я выбрал для отраслевого решения сферу гостини...,3,2,2,2,3,2
...,...,...,...,...,...,...,...,...,...
95,1,97,Я выбрал отрасль грузоперевозок. Целевая аудит...,2,2,4,3,1,2
96,1,98,Я выбрал отрасль ремонта техники. Целевая ауди...,3,2,3,2,2,2
97,1,99,Я выбрал отрасль такси. Целевая аудитория: вод...,1,1,4,3,1,2
98,1,100,Я выбрал отрасль ремонта квартир. Целевая ауди...,3,3,3,2,2,3
99,1,101,Я выбрал отрасль онлайн-магазинов. Целевая ауд...,4,4,4,3,1,3

In [ ]:
df["Оценка"].value_counts()

Оценка
4     208
3     206
1     110
2     105
5      94
7      26
6      21
8      21
9      18
10      6
Name: count, dtype: Int64

In [2]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 9.5 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import Pipeline
from catboost import CatBoostRegressor
import pickle

In [14]:
y_audience = df['ЦА'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_audience, X_test_text_audience, y_train_audience, y_test_audience = train_test_split(
    X_text, y_audience, test_size=0.2, random_state=42
)
tfidf_audience = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_audience = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_audience = tfidf_audience.fit_transform(X_train_text_audience)
#X_train_svd_audience = svd_audience.fit_transform(X_train_tfidf_audience)
X_test_tfidf_audience = tfidf_audience.transform(X_test_text_audience)
#X_test_svd_audience = svd_audience.transform(X_test_tfidf_audience)

In [5]:
from sklearn.model_selection import GridSearchCV

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [7]:
from catboost import CatBoostClassifier

In [8]:
from catboost import CatBoostRegressor

In [9]:
from sklearn.metrics import mean_absolute_error

In [10]:
model_audience = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.1,
    depth=3,
    loss_function='RMSE',
    eval_metric='RMSE',
    early_stopping_rounds=50,
    verbose=50,
    random_seed=42
)

In [15]:
model_audience.fit(X_train_tfidf_audience , y_train_audience)

0:	learn: 1.2614099	total: 16.7ms	remaining: 16.7s
50:	learn: 0.7540657	total: 891ms	remaining: 16.6s
100:	learn: 0.6636427	total: 2.34s	remaining: 20.8s
150:	learn: 0.5970605	total: 3.26s	remaining: 18.3s
200:	learn: 0.5483432	total: 4.1s	remaining: 16.3s
250:	learn: 0.5087752	total: 4.96s	remaining: 14.8s
300:	learn: 0.4799644	total: 5.76s	remaining: 13.4s
350:	learn: 0.4501595	total: 6.65s	remaining: 12.3s
400:	learn: 0.4240482	total: 7.49s	remaining: 11.2s
450:	learn: 0.4007938	total: 8.31s	remaining: 10.1s
500:	learn: 0.3795024	total: 9.14s	remaining: 9.11s
550:	learn: 0.3620830	total: 9.98s	remaining: 8.13s
600:	learn: 0.3453451	total: 10.8s	remaining: 7.2s
650:	learn: 0.3299549	total: 11.7s	remaining: 6.25s
700:	learn: 0.3150313	total: 12.5s	remaining: 5.32s
750:	learn: 0.3014042	total: 13.8s	remaining: 4.57s
800:	learn: 0.2885785	total: 14.9s	remaining: 3.69s
850:	learn: 0.2759281	total: 15.8s	remaining: 2.76s
900:	learn: 0.2650130	total: 16.7s	remaining: 1.83s
950:	learn: 0.2528880	total: 17.5s	remaining: 902ms
999:	learn: 0.2427472	total: 18.3s	remaining: 0us

CatBoostRegressor(depth=3, early_stopping_rounds=50, eval_metric='RMSE', iterations=1000, learning_rate=0.1, loss_function='RMSE', random_seed=42, verbose=50)

In [19]:
feature_importances = model_audience.get_feature_importance()
feature_names = tfidf_audience.get_feature_names_out()
importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': feature_importances
}).sort_values('importance', ascending=False)
print(importance_df.head(10))

       feature  importance
116        cjm   19.321287
338         им    6.087234
348   интервью    5.343760
995        это    4.560655
209        все    3.405062
530        нет    2.251553
168  аудитория    2.249101
513       надо    1.682045
187       боль    1.608062
191      будет    1.555607

In [21]:
y_pred_audience = model_audience.predict(X_test_tfidf_audience)
print(mean_absolute_error(y_test_audience, y_pred_audience))

0.4728090786342818

In [22]:
print("train")
y_pred_audience_train = model_audience.predict(X_train_tfidf_audience)
print(mean_absolute_error(y_train_audience, y_pred_audience_train))

train
0.19831928821193812

In [23]:
y_sol= df['Проработка решения'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_sol, X_test_text_sol, y_train_sol, y_test_sol = train_test_split(
    X_text, y_sol, test_size=0.2, random_state=42
)
tfidf_sol = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_sol= TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_sol = tfidf_sol.fit_transform(X_train_text_sol)
#X_train_svd_sol = svd_sol.fit_transform(X_train_tfidf_sol)
X_test_tfidf_sol = tfidf_sol.transform(X_test_text_sol)
#X_test_svd_sol = svd_sol.transform(X_test_tfidf_sol)

In [25]:
model_sol = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.1,
    depth=3,
    loss_function='RMSE',
    eval_metric='RMSE',
    early_stopping_rounds=50,
    verbose=50,
    random_seed=42
)
model_sol.fit(X_train_tfidf_sol , y_train_sol)
y_pred_sol = model_sol.predict(X_test_tfidf_sol)
#y_pred_sol
print(mean_absolute_error(y_test_sol, y_pred_sol))

0:	learn: 1.2644694	total: 25.9ms	remaining: 25.8s
50:	learn: 0.8191480	total: 805ms	remaining: 15s
100:	learn: 0.7155455	total: 1.56s	remaining: 13.9s
150:	learn: 0.6486056	total: 2.34s	remaining: 13.1s
200:	learn: 0.5995782	total: 3.11s	remaining: 12.4s
250:	learn: 0.5565503	total: 3.98s	remaining: 11.9s
300:	learn: 0.5226157	total: 4.8s	remaining: 11.1s
350:	learn: 0.4906102	total: 5.62s	remaining: 10.4s
400:	learn: 0.4615093	total: 6.52s	remaining: 9.74s
450:	learn: 0.4367184	total: 7.56s	remaining: 9.21s
500:	learn: 0.4119693	total: 9.11s	remaining: 9.07s
550:	learn: 0.3883856	total: 10.1s	remaining: 8.25s
600:	learn: 0.3690613	total: 11.8s	remaining: 7.85s
650:	learn: 0.3535267	total: 13.2s	remaining: 7.07s
700:	learn: 0.3366103	total: 14s	remaining: 5.99s
750:	learn: 0.3212238	total: 14.9s	remaining: 4.94s
800:	learn: 0.3056279	total: 15.8s	remaining: 3.92s
850:	learn: 0.2920240	total: 16.7s	remaining: 2.93s
900:	learn: 0.2795792	total: 17.5s	remaining: 1.93s
950:	learn: 0.2684541	total: 18.6s	remaining: 960ms
999:	learn: 0.2584306	total: 19.4s	remaining: 0us
0.5150706460678438

In [27]:
y_pred_sol_train = model_sol.predict(X_train_tfidf_sol)
#y_pred_sol
print(mean_absolute_error(y_train_sol, y_pred_sol_train))

0.2150445889575911

In [29]:
feature_importances = model_sol.get_feature_importance()
feature_names = tfidf_sol.get_feature_names_out()
importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': feature_importances
}).sort_values('importance', ascending=False)
print(importance_df.head(10))

          feature  importance
338            им    6.626600
348      интервью    5.422001
991    экосистема    4.761507
138           ltv    3.737729
992  экосистемный    3.487517
517            не    2.799985
995           это    2.787028
513          надо    2.411214
662     предлагаю    1.857596
116           cjm    1.773210

In [30]:
y_finance= df['Финансовая модель и метрики'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_finance, X_test_text_finance,y_train_finance, y_test_finance = train_test_split(
    X_text, y_finance, test_size=0.2, random_state=42
)
tfidf_finance = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
#svd_finance = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_finance = tfidf_finance.fit_transform(X_train_text_finance)
#X_train_svd_finance = svd_finance.fit_transform(X_train_tfidf_finance)
X_test_tfidf_finance = tfidf_finance.transform(X_test_text_finance)
#X_test_svd_finance = svd_finance.transform(X_test_tfidf_finance)

In [31]:
model_finance = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.1,
    depth=3,
    loss_function='RMSE',
    eval_metric='RMSE',
    early_stopping_rounds=50,
    verbose=50,
    random_seed=42
)
model_finance.fit(X_train_tfidf_finance , y_train_finance)
y_pred_finance = model_finance.predict(X_test_tfidf_finance)
print(mean_absolute_error(y_test_finance, y_pred_finance))

0:	learn: 1.2061884	total: 22.9ms	remaining: 22.8s
50:	learn: 0.7334435	total: 1.39s	remaining: 25.8s
100:	learn: 0.6271794	total: 2.55s	remaining: 22.7s
150:	learn: 0.5610086	total: 3.37s	remaining: 19s
200:	learn: 0.5168525	total: 4.23s	remaining: 16.8s
250:	learn: 0.4835874	total: 5.07s	remaining: 15.1s
300:	learn: 0.4544072	total: 5.89s	remaining: 13.7s
350:	learn: 0.4263098	total: 7.04s	remaining: 13s
400:	learn: 0.4011230	total: 8.4s	remaining: 12.5s
450:	learn: 0.3787318	total: 10.4s	remaining: 12.6s
500:	learn: 0.3611207	total: 12.4s	remaining: 12.3s
550:	learn: 0.3441007	total: 15.1s	remaining: 12.3s
600:	learn: 0.3286421	total: 17s	remaining: 11.3s
650:	learn: 0.3133780	total: 18.5s	remaining: 9.9s
700:	learn: 0.2992509	total: 19.9s	remaining: 8.5s
750:	learn: 0.2866645	total: 21.5s	remaining: 7.13s
800:	learn: 0.2742308	total: 23s	remaining: 5.71s
850:	learn: 0.2635148	total: 24.2s	remaining: 4.24s
900:	learn: 0.2504508	total: 26.3s	remaining: 2.89s
950:	learn: 0.2406571	total: 28s	remaining: 1.45s
999:	learn: 0.2306069	total: 29.5s	remaining: 0us
0.4808913810872216

In [32]:
print("train")
y_pred_finance_train = model_finance.predict(X_train_tfidf_finance)
print(mean_absolute_error(y_train_finance, y_pred_finance_train))

train
0.18984064164230477

In [33]:
feature_importances = model_finance.get_feature_importance()
feature_names = tfidf_finance.get_feature_names_out()
importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': feature_importances
}).sort_values('importance', ascending=False)
print(importance_df.head(10))

            feature  importance
138             ltv    9.883742
287  доказательства    5.035726
469             млн    4.462067
780         руб ltv    4.432087
530             нет    4.162007
338              им    4.161922
348        интервью    2.985291
517              не    2.639278
956              ца    2.435759
995             это    2.120273

In [34]:
y_risks= df['Анализ рисков'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_risks, X_test_text_risks, y_train_risks, y_test_risks = train_test_split(
    X_text, y_risks, test_size=0.2, random_state=42
)
tfidf_risks = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_risks = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_risks = tfidf_risks.fit_transform(X_train_text_risks)
#X_train_svd_risks = svd_risks.fit_transform(X_train_tfidf_risks)
X_test_tfidf_risks = tfidf_risks.transform(X_test_text_risks)
#X_test_svd_risks = svd_risks.transform(X_test_tfidf_risks)

In [35]:
model_risks = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.1,
    depth=3,
    loss_function='RMSE',
    eval_metric='RMSE',
    early_stopping_rounds=50,
    verbose=50,
    random_seed=42
)
model_risks.fit(X_train_tfidf_risks , y_train_risks)
y_pred_risks = model_risks.predict(X_test_tfidf_risks)
print(mean_absolute_error(y_test_risks, y_pred_risks))

0:	learn: 1.2305535	total: 41.3ms	remaining: 41.3s
50:	learn: 0.7618940	total: 1.64s	remaining: 30.6s
100:	learn: 0.6523239	total: 3.31s	remaining: 29.4s
150:	learn: 0.5824383	total: 5.03s	remaining: 28.3s
200:	learn: 0.5326961	total: 7.2s	remaining: 28.6s
250:	learn: 0.4974699	total: 8.83s	remaining: 26.3s
300:	learn: 0.4648938	total: 10.4s	remaining: 24.1s
350:	learn: 0.4373101	total: 12s	remaining: 22.2s
400:	learn: 0.4127758	total: 13.9s	remaining: 20.8s
450:	learn: 0.3913206	total: 15.5s	remaining: 18.9s
500:	learn: 0.3690977	total: 17.1s	remaining: 17.1s
550:	learn: 0.3499102	total: 19s	remaining: 15.4s
600:	learn: 0.3315683	total: 20.6s	remaining: 13.7s
650:	learn: 0.3177647	total: 22.6s	remaining: 12.1s
700:	learn: 0.3037865	total: 24.9s	remaining: 10.6s
750:	learn: 0.2923066	total: 26.9s	remaining: 8.93s
800:	learn: 0.2787274	total: 28.3s	remaining: 7.02s
850:	learn: 0.2648742	total: 30.3s	remaining: 5.3s
900:	learn: 0.2532732	total: 32s	remaining: 3.51s
950:	learn: 0.2424577	total: 33.7s	remaining: 1.73s
999:	learn: 0.2332120	total: 35.4s	remaining: 0us
0.4850350046218216

In [36]:
feature_importances = model_risks.get_feature_importance()
feature_names = tfidf_risks.get_feature_names_out()
importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': feature_importances
}).sort_values('importance', ascending=False)
print(importance_df.head(10))

          feature  importance
995           это    5.224010
643       подушка    4.753090
338            им    4.745709
517            не    4.704502
348      интервью    4.068036
157        анализ    3.065324
764      риски не    2.811006
179  безопасности    2.712704
275           для    1.965026
168     аудитория    1.633688

In [38]:
print("train")
y_pred_risks_train = model_risks.predict(X_train_tfidf_risks)
print(mean_absolute_error(y_train_risks, y_pred_risks_train))

train
0.191596755144282

In [39]:
y_proves= df['Доказательства'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_proves, X_test_text_proves, y_train_proves, y_test_proves = train_test_split(
    X_text, y_proves, test_size=0.2, random_state=42
)
tfidf_proves = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_proves = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_proves = tfidf_proves.fit_transform(X_train_text_proves)
#X_train_svd_proves = svd_proves.fit_transform(X_train_tfidf_proves)
X_test_tfidf_proves = tfidf_proves.transform(X_test_text_proves)
#X_test_svd_proves = svd_proves.transform(X_test_tfidf_proves)

In [40]:
model_proves = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.1,
    depth=3,
    loss_function='RMSE',
    eval_metric='RMSE',
    early_stopping_rounds=50,
    verbose=50,
    random_seed=42
)
model_proves.fit(X_train_tfidf_proves , y_train_proves)
y_pred_proves = model_proves.predict(X_test_tfidf_proves)
print(mean_absolute_error(y_test_proves, y_pred_proves))

0:	learn: 1.2771648	total: 47ms	remaining: 47s
50:	learn: 0.7797398	total: 968ms	remaining: 18s
100:	learn: 0.6836904	total: 1.91s	remaining: 17s
150:	learn: 0.6144370	total: 2.86s	remaining: 16.1s
200:	learn: 0.5635230	total: 3.86s	remaining: 15.3s
250:	learn: 0.5242972	total: 5.5s	remaining: 16.4s
300:	learn: 0.4883988	total: 6.69s	remaining: 15.5s
350:	learn: 0.4569932	total: 8.1s	remaining: 15s
400:	learn: 0.4313583	total: 9.93s	remaining: 14.8s
450:	learn: 0.4102580	total: 11.8s	remaining: 14.4s
500:	learn: 0.3873633	total: 13.6s	remaining: 13.5s
550:	learn: 0.3667547	total: 15.8s	remaining: 12.9s
600:	learn: 0.3476426	total: 18.3s	remaining: 12.1s
650:	learn: 0.3314842	total: 20s	remaining: 10.7s
700:	learn: 0.3164287	total: 21.6s	remaining: 9.22s
750:	learn: 0.3021773	total: 23.2s	remaining: 7.7s
800:	learn: 0.2894010	total: 24.8s	remaining: 6.15s
850:	learn: 0.2771896	total: 26.3s	remaining: 4.6s
900:	learn: 0.2656932	total: 27.9s	remaining: 3.06s
950:	learn: 0.2538971	total: 29.8s	remaining: 1.53s
999:	learn: 0.2447703	total: 31.8s	remaining: 0us
0.4916109368926133

In [41]:
feature_importances = model_proves.get_feature_importance()
feature_names = tfidf_proves.get_feature_names_out()
importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': feature_importances
}).sort_values('importance', ascending=False)
print(importance_df.head(10))

       feature  importance
348   интервью   20.954709
867     ссылок    3.908336
584      опрос    3.204195
338         им    3.021016
995        это    2.969095
157     анализ    2.559209
116        cjm    2.453878
168  аудитория    1.943409
956         ца    1.742384
776        руб    1.478274

In [43]:
print("train")
y_pred_proves_train = model_proves.predict(X_train_tfidf_proves)
print(mean_absolute_error(y_train_proves, y_pred_proves_train))

train
0.20228059318193042

In [ ]:
new_results_df = pd.DataFrame(columns=['Id','Текст_решения','Анализ ЦА','Проработка решения','Финансовая модель и метрики','Анализ рынков','Доказательства','Предсказанная_оценка','Дата'])

In [ ]:
import re

In [ ]:
dec = '''МОЙ ПРОЕКТ

Я хочу сделать бота для школьников. Он будет помогать решать задачи.

Целевая аудитория - школьники. Им это нужно для учебы.

Мое решение - бот в телеграме. Он будет бесплатный. Похожих ботов нет.

Финансы: разработка стоит примерно 500 тысяч рублей. Потом будем зарабатывать на рекламе.

Риски: могут появиться конкуренты. Будем делать лучше.

Доказательства: я сам учился в школе и знаю, что это нужно. Многие мои друзья тоже так думают.'''

In [ ]:
def get_prediction_audience(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_audience.transform([text])
  text_svd = svd_audience.transform(text_tfidf)
  score = model_audience.predict(text_svd)[0]
  return round(score, 2)

In [ ]:
def get_prediction_solution(text):
  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_sol.transform([text])
  text_svd = svd_sol.transform(text_tfidf)
  score = model_sol.predict(text_svd)[0]
  return round(score, 2)

In [ ]:
def get_prediction_finance(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_finance.transform([text])
  text_svd = svd_finance.transform(text_tfidf)
  score = model_finance.predict(text_svd)[0]
  return round(score, 2)

In [ ]:
def get_prediction_risks(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_risks.transform([text])
  text_svd = svd_risks.transform(text_tfidf)
  score = model_risks.predict(text_svd)[0]
  return round(score, 2)

In [ ]:
def get_prediction_proves(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_proves.transform([text])
  text_svd = svd_proves.transform(text_tfidf)
  score = model_proves.predict(text_svd)[0]
  return round(score, 2)

In [ ]:
df_test_cases['pred_audience'] = df_test_cases['Решение кейса'].apply(get_prediction_audience)
df_test_cases['pred_sol'] = df_test_cases['Решение кейса'].apply(get_prediction_solution)
df_test_cases['pred_finance'] = df_test_cases['Решение кейса'].apply(get_prediction_finance)
df_test_cases['pred_risks'] = df_test_cases['Решение кейса'].apply(get_prediction_risks)
df_test_cases['pred_proves'] = df_test_cases['Решение кейса'].apply(get_prediction_proves)

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix,
    cohen_kappa_score
)

In [ ]:
#ЦА
print(mean_absolute_error(df_test_cases['ЦА'], df_test_cases['pred_audience']))

0.6676923076923077

In [ ]:

print(mean_absolute_error(df_test_cases['Проработка решения'], df_test_cases['pred_sol']))

0.6113076923076923

In [ ]:
print(mean_absolute_error(df_test_cases['Финансовая модель'], df_test_cases['pred_finance']))

0.6003076923076922

In [ ]:
print(mean_absolute_error(df_test_cases['Анализ рынков'], df_test_cases['pred_risks']))

0.6704615384615384

In [ ]:
print(mean_absolute_error(df_test_cases['Доказательства'], df_test_cases['pred_proves']))

0.6663076923076924

In [ ]:
sec_dec = """АНАЛИЗ ЦА:
Выделено 3 сегмента:
- Школьники 10-11 класс (45%)
- Студенты (35%)
- Учителя (20%)
Проведен опрос 100 человек.

РЕШЕНИЕ:
Экосистема из 2 продуктов: телеграм бот + дашборд для учителей.
Партнеры: Яндекс.Образование, МФТИ.

ФИНАНСЫ:
CAPEX: 2 млн руб. CAC = 100 руб, LTV = 2000 руб.
Окупаемость: 10 месяцев.

РИСКИ:
Технические (30%) - резервный сервер.

ДОКАЗАТЕЛЬСТВА:
Пилот в школе: NPS = 65.
"""

In [ ]:
df_test_cases["Predict_score"] = round((df_test_cases['pred_audience'] + df_test_cases['pred_sol'] + df_test_cases['pred_finance'] + df_test_cases['pred_risks'] + df_test_cases['pred_proves'])/5)

In [ ]:
print("MAE= ",mean_absolute_error(df_test_cases["Оценка"], df_test_cases["Predict_score"]))

MAE=  0.4076923076923077

In [ ]:
sol_test = """ Я выбрала отрасль кофеен и кофе-точек с собой (кофе на вынос, кофейные киоски, небольшие кофейни на 2–5 столиков). ЦА разделена на две группы. Первая группа — это микробизнес: кофе-байки и кофе-островки с одним сотрудником, работают как ИП или самозанятые. Их проблема в том, что кофейные зерна нужно покупать свежей обжарки каждую неделю, а хорошие обжарщики требуют предоплату 100% за партию от 5 кг, это около 20–30 тысяч рублей единовременно, что для маленькой точки с ежедневной выручкой 5–7 тысяч рублей чувствительно. Вторая группа — это малый бизнес: кофейни с посадочными местами и штатом 2–5 бариста. Их проблема в том, что сезонность спроса сильно различается: зимой продажи выше за счет горячих напитков, а летом люди покупают холодный кофе и чаще берут с собой, но в межсезонье (апрель и октябрь) падение выручки достигает 30%, при этом аренду и зарплату платить надо. Я опиралась на данные исследования «Рынок кофеен России 2024» от компании CoffeeData: рост рынка на 15% за год, количество кофеен достигло 12 тысяч, из них 70% — малый и микробизнес. Также я посмотрел открытую статистику по кофейному рынку на сайте Росстата и несколько статей в профильных телеграм-каналах. В качестве решения я предлагаю продукт «Альфа.Кофе»: кредит на закупку зёрен с отсрочкой первого платежа на 30 дней и с льготным периодом 0% на первые две недели, а также сезонный овердрафт на покрытие аренды в межсезонье на сумму до 100 тысяч рублей. Партнеры — два крупных обжарщика зерна «Coffe Lab» и «Torrefacto», с которыми можно договориться о более выгодных ценах для клиентов банка. Отличие от конкурентов в том, что ни у Сбера, ни у Т-Банка нет специального продукта для кофеен с отсрочкой именно под зерно. По финансам: разработка кредитного продукта обойдется примерно в 6 миллионов рублей, интеграция с партнерами-обжарщиками — в 2 миллиона, маркетинг в кофейных чатах и через конференции бариста — в 2 миллиона. Прогноз: 350 клиентов в первый год, средний доход с клиента — 20 тысяч рублей (за счет процентов по кредиту и эквайринга), выручка — 7 миллионов рублей. Окупаемость — примерно 2,5 года. Риски: конкурентный — другие банки могут запустить похожие продукты; кредитный — часть клиентов может не вернуть деньги, но мы будем проверять по выписке с кофемашины, кто сколько продает. В доказательство я использовал данные CoffeeData и результаты пары интервью с владельцами кофеен в своем городе."""

In [ ]:
predicted_score_audience = get_prediction_audience(sec_dec)
predicted_score_sol = get_prediction_solution(sec_dec)
predicted_score_finance = get_prediction_finance(sec_dec)
predicted_score_risks = get_prediction_risks(sec_dec)
predicted_score_proves = get_prediction_proves(sec_dec)
predicted_score_audience2 = get_prediction_audience(sec_dec)
predicted_score_sol2 = get_prediction_solution(sec_dec)
predicted_score_finance2 = get_prediction_finance(sec_dec)
predicted_score_risks2 = get_prediction_risks(sec_dec)
predicted_score_proves2 = get_prediction_proves(sec_dec)
new_row = pd.DataFrame([{
    'Id': 1,
    'Текст_решения': sec_dec,
    'Анализ ЦА': predicted_score_audience,
    'Проработка решения': predicted_score_sol,
    'Финансовая модель и метрики': predicted_score_finance,
    'Анализ рынков': predicted_score_risks,
    'Доказательства': predicted_score_proves,
    'Предсказанная_оценка': round((predicted_score_audience + predicted_score_sol +
                      predicted_score_finance + predicted_score_risks +
                      predicted_score_proves) / 5),
    'Дата': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
}])
new_row2 = pd.DataFrame([{
    'Id': 1,
    'Текст_решения': sec_dec,
    'Анализ ЦА': predicted_score_audience2,
    'Проработка решения': predicted_score_sol2,
    'Финансовая модель и метрики': predicted_score_finance2,
    'Анализ рынков': predicted_score_risks2,
    'Доказательства': predicted_score_proves2,
    'Предсказанная_оценка': round((predicted_score_audience2 + predicted_score_sol2 +
                      predicted_score_finance2 + predicted_score_risks2 +
                      predicted_score_proves2) / 5),
    'Дата': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
}])
new_results_df = pd.concat([new_results_df, new_row, new_row2], ignore_index=True)
new_results_df.to_excel("новая_таблица.xlsx", index=False)

/tmp/ipykernel_3876/1005490930.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(score)
/tmp/ipykernel_3876/1097642392.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(score)

In [ ]:
new_results_df

,Id,Текст_решения,Анализ ЦА,Проработка решения,Финансовая модель и метрики,Анализ рынков,Доказательства,Предсказанная_оценка,Дата
0,1,АНАЛИЗ ЦА:\nВыделено 3 сегмента:\n- Школьники ...,5,4,4,4,4,4,2026-06-22 15:34:44
1,1,АНАЛИЗ ЦА:\nВыделено 3 сегмента:\n- Школьники ...,5,4,4,4,4,4,2026-06-22 15:34:44