In [2]:
import pandas as pd
import numpy as np
df = pd.read_excel('/content/cases_train2 (12).xlsx')
df['Оценка'] = df['Оценка'].round().astype('Int64')
df_test_cases = pd.read_excel('/content/Test1_2 (3).xlsx')
df_test_cases['Оценка'] = df_test_cases['Оценка'].round().astype('Int64')
#df = pd.read_excel("/content/good table.xlsx")
df.head(100)

,Кейс,Решение,Решение кейса,ЦА,Проработка решения,Финансовая модель и метрики,Анализ рисков,Доказательства,Оценка
0,1,1,Я выбрал отрасль туризма и гостиничного бизнес...,1,1,1,1,1,1
1,1,2,Я выбрал для разработки отраслевого решения сф...,2,2,2,2,2,2
2,1,4,"Я выбрал отрасль образования, а именно сегмент...",2,4,4,3,3,3
3,1,5,Я выбрал отрасль розничной торговли продуктами...,1,3,2,2,1,2
4,1,6,Я выбрал для отраслевого решения сферу гостини...,3,2,2,2,3,2
...,...,...,...,...,...,...,...,...,...
95,1,97,Я выбрал отрасль грузоперевозок. Целевая аудит...,2,2,4,3,1,2
96,1,98,Я выбрал отрасль ремонта техники. Целевая ауди...,3,2,3,2,2,2
97,1,99,Я выбрал отрасль такси. Целевая аудитория: вод...,1,1,4,3,1,2
98,1,100,Я выбрал отрасль ремонта квартир. Целевая ауди...,3,3,3,2,2,3
99,1,101,Я выбрал отрасль онлайн-магазинов. Целевая ауд...,4,4,4,3,1,3

In [ ]:
df["Оценка"].value_counts()

Оценка
4     208
3     206
1     110
2     105
5      94
7      26
6      21
8      21
9      18
10      6
Name: count, dtype: Int64

In [3]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 10.1 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import Pipeline
from catboost import CatBoostRegressor
import pickle

In [5]:
y_audience = df['ЦА'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_audience, X_test_text_audience, y_train_audience, y_test_audience = train_test_split(
    X_text, y_audience, test_size=0.2, random_state=42
)
tfidf_audience = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_audience = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_audience = tfidf_audience.fit_transform(X_train_text_audience)
X_train_svd_audience = svd_audience.fit_transform(X_train_tfidf_audience)
X_test_tfidf_audience = tfidf_audience.transform(X_test_text_audience)
X_test_svd_audience = svd_audience.transform(X_test_tfidf_audience)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [ ]:
from catboost import CatBoostClassifier

In [ ]:
from catboost import CatBoostRegressor

In [ ]:
from sklearn.metrics import mean_absolute_error

In [10]:
model_audience = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.1,
    depth=3,
    loss_function='RMSE',
    eval_metric='RMSE',
    early_stopping_rounds=50,
    verbose=50,
    random_seed=42
)

In [11]:
model_audience.fit(X_train_svd_audience , y_train_audience)

0:	learn: 1.2771585	total: 8.63ms	remaining: 8.62s
50:	learn: 0.8448703	total: 395ms	remaining: 7.34s
100:	learn: 0.7102238	total: 758ms	remaining: 6.75s
150:	learn: 0.6082186	total: 1.11s	remaining: 6.26s
200:	learn: 0.5337852	total: 1.5s	remaining: 5.96s
250:	learn: 0.4749823	total: 2.22s	remaining: 6.61s
300:	learn: 0.4302222	total: 2.71s	remaining: 6.29s
350:	learn: 0.3877491	total: 3.07s	remaining: 5.67s
400:	learn: 0.3501340	total: 3.43s	remaining: 5.13s
450:	learn: 0.3186826	total: 3.81s	remaining: 4.64s
500:	learn: 0.2912429	total: 4.28s	remaining: 4.26s
550:	learn: 0.2663645	total: 4.99s	remaining: 4.07s
600:	learn: 0.2440923	total: 5.68s	remaining: 3.77s
650:	learn: 0.2256698	total: 6.07s	remaining: 3.25s
700:	learn: 0.2080287	total: 6.45s	remaining: 2.75s
750:	learn: 0.1923630	total: 6.82s	remaining: 2.26s
800:	learn: 0.1786788	total: 7.19s	remaining: 1.78s
850:	learn: 0.1657827	total: 7.56s	remaining: 1.32s
900:	learn: 0.1537978	total: 7.93s	remaining: 871ms
950:	learn: 0.1428173	total: 8.29s	remaining: 427ms
999:	learn: 0.1325633	total: 8.66s	remaining: 0us

CatBoostRegressor(depth=3, early_stopping_rounds=50, eval_metric='RMSE', iterations=1000, learning_rate=0.1, loss_function='RMSE', random_seed=42, verbose=50)

In [12]:
y_pred_audience = model_audience.predict(X_test_svd_audience)
print(mean_absolute_error(y_test_audience, y_pred_audience))

0.5279267858107338

In [13]:
print("train")
y_pred_audience_train = model_audience.predict(X_train_svd_audience)
print(mean_absolute_error(y_train_audience, y_pred_audience_train))

train
0.10358530186571427

In [14]:
y_sol= df['Проработка решения'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_sol, X_test_text_sol, y_train_sol, y_test_sol = train_test_split(
    X_text, y_sol, test_size=0.2, random_state=42
)
tfidf_sol = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_sol= TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_sol = tfidf_sol.fit_transform(X_train_text_sol)
X_train_svd_sol = svd_sol.fit_transform(X_train_tfidf_sol)
X_test_tfidf_sol = tfidf_sol.transform(X_test_text_sol)
X_test_svd_sol = svd_sol.transform(X_test_tfidf_sol)

In [15]:
model_sol = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.1,
    depth=3,
    loss_function='RMSE',
    eval_metric='RMSE',
    early_stopping_rounds=50,
    verbose=50,
    random_seed=42
)
model_sol.fit(X_train_svd_sol , y_train_sol)
y_pred_sol = model_sol.predict(X_test_svd_sol)
#y_pred_sol
print(mean_absolute_error(y_test_sol, y_pred_sol))

0:	learn: 1.2675341	total: 44.4ms	remaining: 44.4s
50:	learn: 0.8827754	total: 1.06s	remaining: 19.7s
100:	learn: 0.7448488	total: 1.94s	remaining: 17.3s
150:	learn: 0.6457909	total: 2.72s	remaining: 15.3s
200:	learn: 0.5717278	total: 3.76s	remaining: 14.9s
250:	learn: 0.5079672	total: 4.68s	remaining: 14s
300:	learn: 0.4584960	total: 5.69s	remaining: 13.2s
350:	learn: 0.4165093	total: 6.54s	remaining: 12.1s
400:	learn: 0.3781159	total: 7.05s	remaining: 10.5s
450:	learn: 0.3434319	total: 7.81s	remaining: 9.51s
500:	learn: 0.3168495	total: 8.55s	remaining: 8.51s
550:	learn: 0.2928547	total: 9.3s	remaining: 7.58s
600:	learn: 0.2704991	total: 10.1s	remaining: 6.7s
650:	learn: 0.2487144	total: 11.1s	remaining: 5.96s
700:	learn: 0.2320283	total: 12s	remaining: 5.13s
750:	learn: 0.2168602	total: 12.9s	remaining: 4.26s
800:	learn: 0.2015846	total: 13.5s	remaining: 3.36s
850:	learn: 0.1871912	total: 14.1s	remaining: 2.46s
900:	learn: 0.1727477	total: 14.4s	remaining: 1.58s
950:	learn: 0.1598746	total: 14.8s	remaining: 762ms
999:	learn: 0.1495644	total: 15.2s	remaining: 0us
0.5561390423433282

In [16]:
y_pred_sol_train = model_sol.predict(X_train_svd_sol)
#y_pred_sol
print(mean_absolute_error(y_train_sol, y_pred_sol_train))

0.11684534844737479

In [17]:
y_finance= df['Финансовая модель и метрики'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_finance, X_test_text_finance,y_train_finance, y_test_finance = train_test_split(
    X_text, y_finance, test_size=0.2, random_state=42
)
tfidf_finance = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_finance = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_finance = tfidf_finance.fit_transform(X_train_text_finance)
X_train_svd_finance = svd_finance.fit_transform(X_train_tfidf_finance)
X_test_tfidf_finance = tfidf_finance.transform(X_test_text_finance)
X_test_svd_finance = svd_finance.transform(X_test_tfidf_finance)

In [18]:
model_finance = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.1,
    depth=3,
    loss_function='RMSE',
    eval_metric='RMSE',
    early_stopping_rounds=50,
    verbose=50,
    random_seed=42
)
model_finance.fit(X_train_svd_finance , y_train_finance)
y_pred_finance = model_finance.predict(X_test_svd_finance)
print(mean_absolute_error(y_test_finance, y_pred_finance))

0:	learn: 1.2089811	total: 17.2ms	remaining: 17.2s
50:	learn: 0.7694638	total: 780ms	remaining: 14.5s
100:	learn: 0.6528667	total: 1.5s	remaining: 13.3s
150:	learn: 0.5687555	total: 2.28s	remaining: 12.8s
200:	learn: 0.5064993	total: 3.02s	remaining: 12s
250:	learn: 0.4572734	total: 3.4s	remaining: 10.2s
300:	learn: 0.4183078	total: 3.78s	remaining: 8.78s
350:	learn: 0.3796188	total: 4.14s	remaining: 7.66s
400:	learn: 0.3466785	total: 4.5s	remaining: 6.72s
450:	learn: 0.3153875	total: 4.88s	remaining: 5.95s
500:	learn: 0.2898523	total: 5.25s	remaining: 5.23s
550:	learn: 0.2690563	total: 5.64s	remaining: 4.59s
600:	learn: 0.2484430	total: 6.01s	remaining: 3.99s
650:	learn: 0.2306340	total: 6.38s	remaining: 3.42s
700:	learn: 0.2143641	total: 6.75s	remaining: 2.88s
750:	learn: 0.1982779	total: 7.12s	remaining: 2.36s
800:	learn: 0.1834788	total: 7.48s	remaining: 1.86s
850:	learn: 0.1703463	total: 7.86s	remaining: 1.38s
900:	learn: 0.1588427	total: 8.22s	remaining: 903ms
950:	learn: 0.1482371	total: 8.57s	remaining: 442ms
999:	learn: 0.1384234	total: 8.95s	remaining: 0us
0.5034969309007493

In [19]:
print("train")
y_pred_finance_train = model_finance.predict(X_train_svd_finance)
print(mean_absolute_error(y_train_finance, y_pred_finance_train))

train
0.10810235395319802

In [20]:
y_risks= df['Анализ рисков'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_risks, X_test_text_risks, y_train_risks, y_test_risks = train_test_split(
    X_text, y_risks, test_size=0.2, random_state=42
)
tfidf_risks = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_risks = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_risks = tfidf_risks.fit_transform(X_train_text_risks)
X_train_svd_risks = svd_risks.fit_transform(X_train_tfidf_risks)
X_test_tfidf_risks = tfidf_risks.transform(X_test_text_risks)
X_test_svd_risks = svd_risks.transform(X_test_tfidf_risks)

In [21]:
model_risks = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.1,
    depth=3,
    loss_function='RMSE',
    eval_metric='RMSE',
    early_stopping_rounds=50,
    verbose=50,
    random_seed=42
)
model_risks.fit(X_train_svd_risks , y_train_risks)
y_pred_risks = model_risks.predict(X_test_svd_risks)
print(mean_absolute_error(y_test_risks, y_pred_risks))

0:	learn: 1.2276277	total: 18.5ms	remaining: 18.5s
50:	learn: 0.8052798	total: 783ms	remaining: 14.6s
100:	learn: 0.6728475	total: 1.45s	remaining: 12.9s
150:	learn: 0.5814528	total: 2.2s	remaining: 12.4s
200:	learn: 0.5121636	total: 2.92s	remaining: 11.6s
250:	learn: 0.4546068	total: 3.31s	remaining: 9.88s
300:	learn: 0.4081302	total: 3.69s	remaining: 8.57s
350:	learn: 0.3724463	total: 4.06s	remaining: 7.51s
400:	learn: 0.3407296	total: 4.42s	remaining: 6.61s
450:	learn: 0.3105523	total: 4.81s	remaining: 5.86s
500:	learn: 0.2853885	total: 5.18s	remaining: 5.16s
550:	learn: 0.2631960	total: 5.6s	remaining: 4.56s
600:	learn: 0.2439439	total: 6.3s	remaining: 4.18s
650:	learn: 0.2266007	total: 7s	remaining: 3.75s
700:	learn: 0.2105229	total: 7.44s	remaining: 3.17s
750:	learn: 0.1957357	total: 7.84s	remaining: 2.6s
800:	learn: 0.1810512	total: 8.2s	remaining: 2.04s
850:	learn: 0.1694003	total: 8.56s	remaining: 1.5s
900:	learn: 0.1580630	total: 8.95s	remaining: 983ms
950:	learn: 0.1487684	total: 9.32s	remaining: 480ms
999:	learn: 0.1400901	total: 9.68s	remaining: 0us
0.5213032930423787

In [22]:
print("train")
y_pred_risks_train = model_risks.predict(X_train_svd_risks)
print(mean_absolute_error(y_train_risks, y_pred_risks_train))

train
0.1084463247784681

In [23]:
y_proves= df['Доказательства'].values
X_text = df['Решение кейса'].fillna('').values
X_train_text_proves, X_test_text_proves, y_train_proves, y_test_proves = train_test_split(
    X_text, y_proves, test_size=0.2, random_state=42
)
tfidf_proves = TfidfVectorizer(max_features=1000, ngram_range=(1, 2), min_df=2)
svd_proves = TruncatedSVD(n_components=200, random_state=42)
X_train_tfidf_proves = tfidf_proves.fit_transform(X_train_text_proves)
X_train_svd_proves = svd_proves.fit_transform(X_train_tfidf_proves)
X_test_tfidf_proves = tfidf_proves.transform(X_test_text_proves)
X_test_svd_proves = svd_proves.transform(X_test_tfidf_proves)

In [24]:
model_proves = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.1,
    depth=3,
    loss_function='RMSE',
    eval_metric='RMSE',
    early_stopping_rounds=50,
    verbose=50,
    random_seed=42
)
model_proves.fit(X_train_svd_proves , y_train_proves)
y_pred_proves = model_proves.predict(X_test_svd_proves)
print(mean_absolute_error(y_test_proves, y_pred_proves))

0:	learn: 1.2824130	total: 65.3ms	remaining: 1m 5s
50:	learn: 0.8619570	total: 1.11s	remaining: 20.7s
100:	learn: 0.7329167	total: 1.84s	remaining: 16.4s
150:	learn: 0.6340008	total: 2.48s	remaining: 14s
200:	learn: 0.5574433	total: 3.21s	remaining: 12.8s
250:	learn: 0.5007041	total: 3.93s	remaining: 11.7s
300:	learn: 0.4522839	total: 4.37s	remaining: 10.2s
350:	learn: 0.4097164	total: 4.75s	remaining: 8.78s
400:	learn: 0.3744010	total: 5.49s	remaining: 8.2s
450:	learn: 0.3434251	total: 5.86s	remaining: 7.13s
500:	learn: 0.3153904	total: 6.59s	remaining: 6.56s
550:	learn: 0.2945783	total: 6.95s	remaining: 5.66s
600:	learn: 0.2755473	total: 7.32s	remaining: 4.86s
650:	learn: 0.2519785	total: 7.7s	remaining: 4.13s
700:	learn: 0.2339977	total: 8.07s	remaining: 3.44s
750:	learn: 0.2172406	total: 8.45s	remaining: 2.8s
800:	learn: 0.2018155	total: 8.84s	remaining: 2.19s
850:	learn: 0.1859160	total: 9.21s	remaining: 1.61s
900:	learn: 0.1735958	total: 9.61s	remaining: 1.06s
950:	learn: 0.1603408	total: 9.98s	remaining: 514ms
999:	learn: 0.1498978	total: 10.3s	remaining: 0us
0.5224943769302313

In [25]:
print("train")
y_pred_proves_train = model_proves.predict(X_train_svd_proves)
print(mean_absolute_error(y_train_proves, y_pred_proves_train))

train
0.1165035131632451

In [ ]:
new_results_df = pd.DataFrame(columns=['Id','Текст_решения','Анализ ЦА','Проработка решения','Финансовая модель и метрики','Анализ рынков','Доказательства','Предсказанная_оценка','Дата'])

In [ ]:
import re

In [ ]:
dec = '''МОЙ ПРОЕКТ

Я хочу сделать бота для школьников. Он будет помогать решать задачи.

Целевая аудитория - школьники. Им это нужно для учебы.

Мое решение - бот в телеграме. Он будет бесплатный. Похожих ботов нет.

Финансы: разработка стоит примерно 500 тысяч рублей. Потом будем зарабатывать на рекламе.

Риски: могут появиться конкуренты. Будем делать лучше.

Доказательства: я сам учился в школе и знаю, что это нужно. Многие мои друзья тоже так думают.'''

In [26]:
def get_prediction_audience(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_audience.transform([text])
  text_svd = svd_audience.transform(text_tfidf)
  score = model_audience.predict(text_svd)[0]
  return round(score, 2)

In [27]:
def get_prediction_solution(text):
  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_sol.transform([text])
  text_svd = svd_sol.transform(text_tfidf)
  score = model_sol.predict(text_svd)[0]
  return round(score, 2)

In [28]:
def get_prediction_finance(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_finance.transform([text])
  text_svd = svd_finance.transform(text_tfidf)
  score = model_finance.predict(text_svd)[0]
  return round(score, 2)

In [29]:
def get_prediction_risks(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_risks.transform([text])
  text_svd = svd_risks.transform(text_tfidf)
  score = model_risks.predict(text_svd)[0]
  return round(score, 2)

In [30]:
def get_prediction_proves(text):

  if pd.isna(text) or not isinstance(text, str):
        text = ""
  text_tfidf = tfidf_proves.transform([text])
  text_svd = svd_proves.transform(text_tfidf)
  score = model_proves.predict(text_svd)[0]
  return round(score, 2)

In [31]:
df_test_cases['pred_audience'] = df_test_cases['Решение кейса'].apply(get_prediction_audience)
df_test_cases['pred_sol'] = df_test_cases['Решение кейса'].apply(get_prediction_solution)
df_test_cases['pred_finance'] = df_test_cases['Решение кейса'].apply(get_prediction_finance)
df_test_cases['pred_risks'] = df_test_cases['Решение кейса'].apply(get_prediction_risks)
df_test_cases['pred_proves'] = df_test_cases['Решение кейса'].apply(get_prediction_proves)

In [32]:
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix,
    cohen_kappa_score
)

In [33]:
#ЦА
print(mean_absolute_error(df_test_cases['ЦА'], df_test_cases['pred_audience']))

0.6676923076923077

In [34]:

print(mean_absolute_error(df_test_cases['Проработка решения'], df_test_cases['pred_sol']))

0.6113076923076923

In [35]:
print(mean_absolute_error(df_test_cases['Финансовая модель'], df_test_cases['pred_finance']))

0.6003076923076922

In [36]:
print(mean_absolute_error(df_test_cases['Анализ рынков'], df_test_cases['pred_risks']))

0.6704615384615384

In [37]:
print(mean_absolute_error(df_test_cases['Доказательства'], df_test_cases['pred_proves']))

0.6663076923076924

In [ ]:
sec_dec = """АНАЛИЗ ЦА:
Выделено 3 сегмента:
- Школьники 10-11 класс (45%)
- Студенты (35%)
- Учителя (20%)
Проведен опрос 100 человек.

РЕШЕНИЕ:
Экосистема из 2 продуктов: телеграм бот + дашборд для учителей.
Партнеры: Яндекс.Образование, МФТИ.

ФИНАНСЫ:
CAPEX: 2 млн руб. CAC = 100 руб, LTV = 2000 руб.
Окупаемость: 10 месяцев.

РИСКИ:
Технические (30%) - резервный сервер.

ДОКАЗАТЕЛЬСТВА:
Пилот в школе: NPS = 65.
"""

In [39]:
df_test_cases["Predict_score"] = round((df_test_cases['pred_audience'] + df_test_cases['pred_sol'] + df_test_cases['pred_finance'] + df_test_cases['pred_risks'] + df_test_cases['pred_proves'])/5)

In [40]:
print("MAE= ",mean_absolute_error(df_test_cases["Оценка"], df_test_cases["Predict_score"]))

MAE=  0.4076923076923077

In [ ]:
sol_test = """ Я выбрала отрасль кофеен и кофе-точек с собой (кофе на вынос, кофейные киоски, небольшие кофейни на 2–5 столиков). ЦА разделена на две группы. Первая группа — это микробизнес: кофе-байки и кофе-островки с одним сотрудником, работают как ИП или самозанятые. Их проблема в том, что кофейные зерна нужно покупать свежей обжарки каждую неделю, а хорошие обжарщики требуют предоплату 100% за партию от 5 кг, это около 20–30 тысяч рублей единовременно, что для маленькой точки с ежедневной выручкой 5–7 тысяч рублей чувствительно. Вторая группа — это малый бизнес: кофейни с посадочными местами и штатом 2–5 бариста. Их проблема в том, что сезонность спроса сильно различается: зимой продажи выше за счет горячих напитков, а летом люди покупают холодный кофе и чаще берут с собой, но в межсезонье (апрель и октябрь) падение выручки достигает 30%, при этом аренду и зарплату платить надо. Я опиралась на данные исследования «Рынок кофеен России 2024» от компании CoffeeData: рост рынка на 15% за год, количество кофеен достигло 12 тысяч, из них 70% — малый и микробизнес. Также я посмотрел открытую статистику по кофейному рынку на сайте Росстата и несколько статей в профильных телеграм-каналах. В качестве решения я предлагаю продукт «Альфа.Кофе»: кредит на закупку зёрен с отсрочкой первого платежа на 30 дней и с льготным периодом 0% на первые две недели, а также сезонный овердрафт на покрытие аренды в межсезонье на сумму до 100 тысяч рублей. Партнеры — два крупных обжарщика зерна «Coffe Lab» и «Torrefacto», с которыми можно договориться о более выгодных ценах для клиентов банка. Отличие от конкурентов в том, что ни у Сбера, ни у Т-Банка нет специального продукта для кофеен с отсрочкой именно под зерно. По финансам: разработка кредитного продукта обойдется примерно в 6 миллионов рублей, интеграция с партнерами-обжарщиками — в 2 миллиона, маркетинг в кофейных чатах и через конференции бариста — в 2 миллиона. Прогноз: 350 клиентов в первый год, средний доход с клиента — 20 тысяч рублей (за счет процентов по кредиту и эквайринга), выручка — 7 миллионов рублей. Окупаемость — примерно 2,5 года. Риски: конкурентный — другие банки могут запустить похожие продукты; кредитный — часть клиентов может не вернуть деньги, но мы будем проверять по выписке с кофемашины, кто сколько продает. В доказательство я использовал данные CoffeeData и результаты пары интервью с владельцами кофеен в своем городе."""

In [ ]:
predicted_score_audience = get_prediction_audience(sec_dec)
predicted_score_sol = get_prediction_solution(sec_dec)
predicted_score_finance = get_prediction_finance(sec_dec)
predicted_score_risks = get_prediction_risks(sec_dec)
predicted_score_proves = get_prediction_proves(sec_dec)
predicted_score_audience2 = get_prediction_audience(sec_dec)
predicted_score_sol2 = get_prediction_solution(sec_dec)
predicted_score_finance2 = get_prediction_finance(sec_dec)
predicted_score_risks2 = get_prediction_risks(sec_dec)
predicted_score_proves2 = get_prediction_proves(sec_dec)
new_row = pd.DataFrame([{
    'Id': 1,
    'Текст_решения': sec_dec,
    'Анализ ЦА': predicted_score_audience,
    'Проработка решения': predicted_score_sol,
    'Финансовая модель и метрики': predicted_score_finance,
    'Анализ рынков': predicted_score_risks,
    'Доказательства': predicted_score_proves,
    'Предсказанная_оценка': round((predicted_score_audience + predicted_score_sol +
                      predicted_score_finance + predicted_score_risks +
                      predicted_score_proves) / 5),
    'Дата': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
}])
new_row2 = pd.DataFrame([{
    'Id': 1,
    'Текст_решения': sec_dec,
    'Анализ ЦА': predicted_score_audience2,
    'Проработка решения': predicted_score_sol2,
    'Финансовая модель и метрики': predicted_score_finance2,
    'Анализ рынков': predicted_score_risks2,
    'Доказательства': predicted_score_proves2,
    'Предсказанная_оценка': round((predicted_score_audience2 + predicted_score_sol2 +
                      predicted_score_finance2 + predicted_score_risks2 +
                      predicted_score_proves2) / 5),
    'Дата': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
}])
new_results_df = pd.concat([new_results_df, new_row, new_row2], ignore_index=True)
new_results_df.to_excel("новая_таблица.xlsx", index=False)

/tmp/ipykernel_3876/1005490930.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(score)
/tmp/ipykernel_3876/1097642392.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(score)

In [ ]:
new_results_df

,Id,Текст_решения,Анализ ЦА,Проработка решения,Финансовая модель и метрики,Анализ рынков,Доказательства,Предсказанная_оценка,Дата
0,1,АНАЛИЗ ЦА:\nВыделено 3 сегмента:\n- Школьники ...,5,4,4,4,4,4,2026-06-22 15:34:44
1,1,АНАЛИЗ ЦА:\nВыделено 3 сегмента:\n- Школьники ...,5,4,4,4,4,4,2026-06-22 15:34:44